/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.28
 * Generated at: 2015-12-18 06:03:38 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.manage.xinxi;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.baje.sz.ajax.AjaxXml;
import com.baje.sz.util.Doc;
import com.baje.sz.util.RequestUtil;
import com.hanyou.admin.sys.News;
import java.util.Iterator;
import java.util.List;
import com.baje.sz.util.*;
import com.baje.sz.ajax.*;
import com.hanyou.admin.sys.*;

public final class news_005fedit_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/manage/xinxi/../ini_sys.jsp", Long.valueOf(1448868343606L));
    _jspx_dependants.put("/manage/xinxi/../end.jsp", Long.valueOf(1448868342872L));
    _jspx_dependants.put("/manage/xinxi/../left.jsp", Long.valueOf(1450407753560L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("com.hanyou.admin.sys");
    _jspx_imports_packages.add("com.baje.sz.ajax");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("com.baje.sz.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.Iterator");
    _jspx_imports_classes.add("com.baje.sz.ajax.AjaxXml");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.hanyou.admin.sys.News");
    _jspx_imports_classes.add("com.baje.sz.util.Doc");
    _jspx_imports_classes.add("com.baje.sz.util.RequestUtil");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

    request.setCharacterEncoding("utf-8");
    AdminLogin checklogin = new AdminLogin();
    int userid = 0;
    String user_name = "guest";
    String current_flags = "";
    int gym_group_id = 0, gym_id = 0;
    Selectic utildb = new Selectic();
    Doc currentUser = null;
    int ii = checklogin.checkLogin(request, response);
    if (ii == 0) {
        user_name = checklogin.getuser_name();
        userid = checklogin.getuserid();

        currentUser = utildb.Get_Doc("user_flag,gym_group_id,gym_id", "hy_sys_user", "where id=" + userid, "mysqlss");
        //System.out.println("currentUser="+currentUser);
        if (currentUser != null) {
            current_flags = AjaxXml.getString(currentUser.get("user_flag"));
            //System.out.println("current_flags="+current_flags);
            gym_group_id = currentUser.getIn("gym_group_id");
            gym_id = currentUser.getIn("gym_id");

        }
        //flag=admin_username.get("flag");
    } else {
        out.print("<script>");
        out.print("alert('请登录后再操作');");
        out.print("window.parent.location = '/manage/login.jsp'");
        out.print("</script>");
        return;
    }

      out.write('\r');
      out.write('\n');

    response.setHeader("Pragma", "No-cache");
    response.setHeader("Cache-Control", "no-cache");
    response.setDateHeader("Expires", 0);
    if (current_flags.indexOf(",4002,") < 0) {
        response.sendRedirect("../error.jsp?left=xinxi");
        return;
    }
    RequestUtil ru = new RequestUtil(request);
    News ste = new News();
    String action = ru.getString("action");
    if (action.equals("save")) {
        String result = ste.editNews(request, userid, user_name, gym_group_id, gym_id);
        out.print(result);
        return;
    }

    int newsclass = 0;
    String newstitle = "", bossname = "", smallfile = "", bigfile = "";
    int ordernum = 0, isdel = 0;
    String addtime = "", adduser = "";
    int adduserid = 0;
    String templet = "", savepath = "", htmlpage = "", classnavicontent = "", content = "", urladdress = "";
    int newstype = 0;
    String keywords = "";
//double saleprice=0,marketprice=0,inprice=0;
//int jifen=0,salecount=0,kucun=0;
//String danwei="",lastuserpost="",lasttime="";
//int newszan=0,fenxiang=0,hits=0,child=0;
//String keywords="";

    int id = ru.getInt("id");
    action = "save";
    if (id > 0) {
        Doc doc = utildb.Get_Doc("id,newstitle,newsclass,bossname,smallfile,bigfile,ordernum,isdel,addtime,adduser,adduserid,templet,savepath,htmlpage,classnavicontent," +
                "content,newstype,hits,child,keywords,urladdress" +
                "", "hy_news", "where id=?", "", new Object[]{new Integer(id)});
        if (doc != null) {
            newstitle = doc.get("newstitle");
            content = doc.get("content");
            newsclass = doc.getIn("newsclass");
            keywords = doc.get("keywords");
            bossname = doc.get("bossname");
            smallfile = doc.get("smallfile");
            bigfile = doc.get("bigfile");

            ordernum = doc.getIn("ordernum");
            isdel = doc.getIn("isdel");
            addtime = doc.get("addtime");
            adduser = doc.get("adduser");

            templet = AjaxXml.getString(doc.get("templet"));
            savepath = doc.get("savepath");
            urladdress = doc.get("urladdress");
            classnavicontent = AjaxXml.getString(doc.get("classnavicontent"));

        }
    }
    String logstarttime = AjaxXml.Get_Date("now", "YY04-MM-DD HH:MI:SS");

      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\"/>\r\n");
      out.write("    <title>table</title>\r\n");
      out.write("    <link href=\"../css/reset.css\" rel=\"stylesheet\" type=\"text/css\"/>\r\n");
      out.write("    <link href=\"../css/base.css\" rel=\"stylesheet\" type=\"text/css\"/>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <script type=\"text/javascript\" src=\"../js/jquery-1.7.2.min.js\"></script>\r\n");
      out.write("    <script language=\"javascript\" src='../js/sys.js'></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"/public/js/ueditor1_2_3_0/editor_config.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"/public/js/ueditor1_2_3_0/editor_all.js\"></script>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/public/js/ueditor1_2_3_0/themes/default/ueditor.css\"/>\r\n");
      out.write("    <script type='text/javascript' src='/public/js/global.js'></script>\r\n");
      out.write("    <link type=\"text/css\" rel=\"stylesheet\" href=\"/public/js/jquery.alerts.css\"/>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"/public/js/jquery.alerts.js\"></script>\r\n");
      out.write("    <link href='/public/js/operamasks/operamasks-ui.css' rel='stylesheet' type='text/css'/>\r\n");
      out.write("    <script type='text/javascript' src='/public/js/operamasks/operamasks-ui.min.js'></script>\r\n");
      out.write("    <style type=\"text/css\">\r\n");
      out.write("        .del {\r\n");
      out.write("            bottom: 0;\r\n");
      out.write("            height: 22px;\r\n");
      out.write("            width: 100px;\r\n");
      out.write("            line-height: 22px;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            background: #000;\r\n");
      out.write("            color: #fff;\r\n");
      out.write("            filter: alpha(opacity=70);\r\n");
      out.write("            -moz-opacity: 0.7;\r\n");
      out.write("            -khtml-opacity: 0.7;\r\n");
      out.write("            opacity: 0.7;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("        function selectPicBack(inputname, inputvalue) {\r\n");
      out.write("            $(\"#windownbg\").remove();\r\n");
      out.write("            $(\"#windown-box\").fadeOut(\"slow\", function () {\r\n");
      out.write("                $(this).remove();\r\n");
      out.write("            });\r\n");
      out.write("            $(\"#\" + inputname).attr(\"value\", inputvalue);\r\n");
      out.write("        }\r\n");
      out.write("        function uppic(inputname) {\r\n");
      out.write("            openurl('../uppic.jsp?backinput=' + inputname + '', 'pic', '上传图片', 400, 180, 0, 50, true);\r\n");
      out.write("        }\r\n");
      out.write("        function selectPicBack(inputname, urlpath) {\r\n");
      out.write("            if (urlpath != \"\") {\r\n");
      out.write("                $(\"#\" + inputname).val(urlpath);\r\n");
      out.write("            }\r\n");
      out.write("            art.dialog({id: \"pic\"}).close();\r\n");
      out.write("        }\r\n");
      out.write("        function usersave() {\r\n");
      out.write("            var id = $(\"#id\").val();\r\n");
      out.write("            var newsclass = $(\"#newsclass\").val();\r\n");
      out.write("            var newstitle = $(\"#newstitle\").val();\r\n");
      out.write("            var bossname = $(\"#bossname\").val();\r\n");
      out.write("            var paixu = $(\"#paixu\").val();\r\n");
      out.write("            //var content=KE.util.getData('content');\r\n");
      out.write("            var content = escape(escape(editor.getContent()));\r\n");
      out.write("            if (newsclass == \"\" || newsclass == \"0\") {\r\n");
      out.write("                window.parent.art.dialog.alert('请选择栏目');\r\n");
      out.write("                return;\r\n");
      out.write("            }\r\n");
      out.write("            if (newstitle == \"\") {\r\n");
      out.write("                window.parent.art.dialog.alert('请输入标题');\r\n");
      out.write("                return;\r\n");
      out.write("            }\r\n");
      out.write("            if (content == \"\") {\r\n");
      out.write("                content = \"<p></p>\"\r\n");
      out.write("            }\r\n");
      out.write("            String.prototype.replaceAll = function (s1, s2) {\r\n");
      out.write("                return this.replace(new RegExp(s1, \"gm\"), s2);\r\n");
      out.write("            }\r\n");
      out.write("            content = content.replaceAll(\"&\", \"^…\");\r\n");
      out.write("            $(\"#tjbutton\").attr(\"disabled\", true);\r\n");
      out.write("            $(\"#tisspan\").html(\"<img src='../images/loading.gif' />提交中，请稍候……\");\r\n");
      out.write("            $.ajax({\r\n");
      out.write("                type: \"post\",\r\n");
      out.write("                url: \"news_edit.jsp\",\r\n");
      out.write("                data: $(\"#form1\").serialize() + \"&logstarttime=");
      out.print(logstarttime);
      out.write("&contentx=\" + content + \"\",\r\n");
      out.write("\r\n");
      out.write("                //data:\"id=\"+id+\"&action=save&newsclass=\"+newsclass+\"&title=\"+title+\"&bossname=\"+bossname+\"&markpic=\"+markpic+\"&content=\"+content+\"&paixu=\"+paixu+\"&logstarttime=");
      out.print(logstarttime);
      out.write("\",\r\n");
      out.write("                success: function (msg) {\r\n");
      out.write("                    var backarr = $.trim(msg).split(\"$$\");\r\n");
      out.write("                    if (backarr[1] == \"ok\") {\r\n");
      out.write("                        window.parent.art.dialog({\r\n");
      out.write("                            id: 'tisID',\r\n");
      out.write("                            content: backarr[0],\r\n");
      out.write("                            lock: true,\r\n");
      out.write("                            icon: \"succeed\",\r\n");
      out.write("                            cancelVal: '确定',\r\n");
      out.write("                            cancel: function () {\r\n");
      out.write("                                $(\"#tjbutton\").attr(\"disabled\", false);\r\n");
      out.write("                                $(\"#tisspan\").html(\"\");\r\n");
      out.write("                                //window.parent.location.reload();\r\n");
      out.write("                                window.parent.art.dialog({id: \"tisID\"}).close();\r\n");
      out.write("                                //window.parent.art.dialog({id:\"xitong\"}).close();\r\n");
      out.write("                                window.parent.jianyi2('/manage/xinxi/news.jsp', '信息内容');\r\n");
      out.write("                                window.parent.tabclose(\"编辑新闻\");\r\n");
      out.write("                            }\r\n");
      out.write("                        });\r\n");
      out.write("                    } else {\r\n");
      out.write("                        window.parent.art.dialog.alert(backarr[0]);\r\n");
      out.write("                        $(\"#tjbutton\").attr(\"disabled\", false);\r\n");
      out.write("                        $(\"#tisspan\").html(\"\");\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                }\r\n");
      out.write("            });\r\n");
      out.write("        }\r\n");
      out.write("    </script>\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"ifr\">\r\n");
      out.write("\r\n");
      out.write("<link href=\"/manage/css/colortemplate.css\" rel=\"stylesheet\" type=\"text/css\"/>\r\n");
      out.write("<div class=\"sidebarWrap\">\r\n");
      out.write("    <div class=\"sidebar\" id=\"yonghu\" style=\"display:none\">\r\n");
      out.write("        <h3>\r\n");
      out.write("            <span>用户管理</span>\r\n");
      out.write("        </h3>\r\n");
      out.write("        <ul class=\"nav_list\">\r\n");
      out.write("\r\n");
      out.write("            ");

                if (current_flags.contains("1001")) {
            
      out.write("\r\n");
      out.write("            <li><a href=\"javascript:window.parent.jianyi2('yonghu/yonghu.jsp','用户管理')\">用户管理</a></li>\r\n");
      out.write("            ");

                }
                if (current_flags.contains("1004")) {
            
      out.write("\r\n");
      out.write("             <li><a href=\"javascript:window.parent.jianyi2('yonghu/level_experience_group.jsp?group_type=1','积分操作组别')\">积分操作组别</a></li>\r\n");
      out.write("            ");

                }
                if (current_flags.contains("1005")) {
            
      out.write("\r\n");
      out.write("           <li><a href=\"javascript:window.parent.jianyi2('yonghu/level_experience_operating.jsp?operating_type=1','积分操作')\">积分操作</a></li>\r\n");
      out.write("            ");

                }
                if (current_flags.contains("1007")) {
            
      out.write("\r\n");
      out.write("             <li><a href=\"javascript:window.parent.jianyi2('yonghu/level_experience_operating_user.jsp?operating_type=1','积分获取情况')\">积分获取情况</a></li>\r\n");
      out.write("            ");

                }
               
      out.write("\r\n");
      out.write("        </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"sidebar\" id=\"jianshenfang\" style=\"display:none\">\r\n");
      out.write("        <h3>\r\n");
      out.write("            <span>健身房管理</span>\r\n");
      out.write("        </h3>\r\n");
      out.write("        <ul class=\"nav_list\">\r\n");
      out.write("            ");

                if (gym_group_id == 0) {
                    if (current_flags.contains("3001")) {
            
      out.write("\r\n");
      out.write("            <li><a href=\"javascript:window.parent.jianyi2('jianshenfang/jituan.jsp','连锁集团管理')\">连锁集团管理</a></li>\r\n");
      out.write("            ");

                    }
                }
						/*  if(gym_id==0){  */
                if (current_flags.contains("3005")) {
            
      out.write("\r\n");
      out.write("            <li><a href=\"javascript:window.parent.jianyi2('jianshenfang/gym.jsp','健身房管理')\">健身房管理</a></li>\r\n");
      out.write("            ");

                }
					 /* 	}  */
                if (current_flags.contains("3009")) {
            
      out.write("\r\n");
      out.write("            <li><a href=\"javascript:window.parent.jianyi2('jianshenfang/coach.jsp','教练管理')\">教练管理</a></li>\r\n");
      out.write("            ");
}
				if (current_flags.contains("3045")) { 
				
      out.write("\r\n");
      out.write("            <li><a href=\"javascript:window.parent.jianyi2('jianshenfang/device.jsp','设备管理')\">设备管理</a></li>\r\n");
      out.write("            ");

                 }
                 if (current_flags.contains("3049")) {
             
      out.write("\r\n");
      out.write("             <li>\r\n");
      out.write("                 <a href=\"javascript:window.parent.jianyi2('jianshenfang/bodyMeasure_titai.jsp', '体态管理')\">体态管理</a>\r\n");
      out.write("             </li>\r\n");
      out.write("             ");

                 } 
                 if(current_flags.contains("3050")){
                 	
      out.write("\r\n");
      out.write("                 \t <li>\r\n");
      out.write("                 <a href=\"javascript:window.parent.jianyi2('jianshenfang/bodyMeasure_tineng.jsp', '体能管理')\">体能管理</a>\r\n");
      out.write("             </li>\r\n");
      out.write("                 \t");

                 }
                 if(current_flags.contains("3051")){
              		
      out.write("\r\n");
      out.write("              \t\t  <li><a href=\"javascript:window.parent.jianyi2('jianshenfang/bodyMeasure_tice.jsp', '体测管理')\">体测管理</a>\r\n");
      out.write("            \t\t\t\t </li>\r\n");
      out.write("              \t\t");

                 }
                if (current_flags.contains("3017")) {
            
      out.write("\r\n");
      out.write("            <li>\r\n");
      out.write("                <a href=\"javascript:window.parent.jianyi2('jianshenfang/gym_member_book.jsp?book_type=1','预约私教')\">预约私教</a>\r\n");
      out.write("            </li>\r\n");
      out.write("            ");
 
                }
            
      out.write("\r\n");
      out.write("        </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"sidebar\" id=\"order\" style=\"display:none\">\r\n");
      out.write("        <h3>\r\n");
      out.write("            <span>订单管理</span>\r\n");
      out.write("        </h3>\r\n");
      out.write("        <ul class=\"nav_list\">\r\n");
      out.write("            ");
if (current_flags.contains("2007")) { 
      out.write("\r\n");
      out.write("            <li><a href=\"javascript:window.parent.jianyi2('order/hy_order.jsp','订单管理')\">订单管理</a></li>\r\n");
      out.write("            ");

                }
                if (current_flags.contains("2026")) {
            
      out.write("\r\n");
      out.write("            <li><a href=\"javascript:window.parent.jianyi2('order/plan_action_type.jsp','动作类型')\">动作类型</a></li>\r\n");
      out.write("            ");

                }
                if (current_flags.contains("2027")) {
            
      out.write("\r\n");
      out.write("            <li><a href=\"javascript:window.parent.jianyi2('order/default_action.jsp','默认动作')\">默认动作</a></li>\r\n");
      out.write("            ");

                }
                if (current_flags.contains("2028")) {
            
      out.write("\r\n");
      out.write("            <li><a href=\"javascript:window.parent.jianyi2('order/plan_action_type.jsp?type=1','健身目标')\">健身目标</a></li>\r\n");
      out.write("             ");
} if (current_flags.contains("2029")) {
                            
      out.write("\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"javascript:window.parent.jianyi2('order/common_language_class.jsp?','常用语类型')\">常用语类型</a>\r\n");
      out.write("                            </li>");

                } if(current_flags.contains("2030")){
                	
      out.write("\r\n");
      out.write("                \t <li>\r\n");
      out.write("                    \t<a href=\"javascript:window.parent.jianyi2('order/common_language.jsp','常用语设置')\">常用语设置</a>\r\n");
      out.write("                \t</li>\r\n");
      out.write("                \t");

                	
                } 
      out.write("\r\n");
      out.write("                \r\n");
      out.write("\t\t\t\t\t     <li><a href=\"javascript:window.parent.jianyi2('order/pro_class.jsp?class_status=1','商品栏目')\">商品栏目</a></li>\r\n");
      out.write("\t\t\t\t\t     <li><a href=\"javascript:window.parent.jianyi2('order/pro_product.jsp','商品管理')\">商品管理</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("    ");

        if (current_flags.contains("4004")) {
    
      out.write("\r\n");
      out.write("    <div class=\"sidebar\" id=\"xinxi\" style=\"display:none\">\r\n");
      out.write("        <h3>\r\n");
      out.write("            <span>信息管理</span>\r\n");
      out.write("        </h3>\r\n");
      out.write("        <ul class=\"nav_list\">\r\n");
      out.write("            ");
 if (current_flags.contains("4002")) {
      out.write("\r\n");
      out.write("            <li><a href=\"javascript:window.parent.jianyi2('xinxi/news.jsp','信息内容')\">信息内容</a></li>\r\n");
      out.write("            ");

                }
                if (current_flags.contains("4001")) {
            
      out.write("\r\n");
      out.write("            <li><a href=\"javascript:window.parent.jianyi2('xinxi/newsclass.jsp','信息栏目')\">信息栏目</a></li>\r\n");
      out.write("\r\n");
      out.write("            ");

                }
                if (current_flags.contains("4003")) {
            
      out.write("\r\n");
      out.write("            <li><a href=\"javascript:window.parent.jianyi2('xinxi/news_edit.jsp','发布信息')\">发布信息</a></li>\r\n");
      out.write("            ");

                }
            
      out.write("\r\n");
      out.write("        </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("    ");

        }
    
      out.write("\r\n");
      out.write("    <div class=\"sidebar\" id=\"faxian\" style=\"display:none\">\r\n");
      out.write("        <h3>\r\n");
      out.write("            <span>发现管理</span>\r\n");
      out.write("        </h3>\r\n");
      out.write("        <ul class=\"nav_list\">\r\n");
      out.write("            ");
 if (current_flags.contains("5001")) { 
      out.write("\r\n");
      out.write("            <li><a href=\"javascript:window.parent.jianyi2('faxian/wenzhang.jsp','发现文章')\">发现文章</a></li>\r\n");
      out.write("            ");

                }
                if (current_flags.contains("5005")) {
            
      out.write("\r\n");
      out.write("            <li><a href=\"javascript:window.parent.jianyi2('faxian/huifu.jsp','文章评论')\">文章评论</a></li>\r\n");
      out.write("            ");

                }
                if (current_flags.contains("5007")) {
            
      out.write("\r\n");
      out.write("            <li><a href=\"javascript:window.parent.jianyi2('faxian/hy_friendster_carousel.jsp','每日推荐')\">每日推荐</a></li>\r\n");
      out.write("            ");
} 
      out.write("\r\n");
      out.write("        </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"sidebar\" id=\"xitong\" style=\"display:none\">\r\n");
      out.write("\r\n");
      out.write("        <h3>\r\n");
      out.write("            <span>系统管理管理</span>\r\n");
      out.write("        </h3>\r\n");
      out.write("        <ul class=\"nav_list\">\r\n");
      out.write("            ");
if (current_flags.contains("6001")) { 
      out.write("\r\n");
      out.write("            <li><a href=\"javascript:window.parent.jianyi2('xitong/rizhi.jsp','系统日志')\">系统日志</a></li>\r\n");
      out.write("            <li><a href=\"javascript:window.parent.jianyi2('xitong/rizhi.jsp?log_type=2','教练系统日志')\">教练系统日志</a></li>\r\n");
      out.write("            ");

                }
                if (current_flags.contains("6002")) {
            
      out.write("\r\n");
      out.write("            <li><a href=\"javascript:window.parent.jianyi2('xitong/keyword.jsp','关键词管理')\">关键词管理</a></li>\r\n");
      out.write("            ");

                }
                if (current_flags.contains("6009")) {
            
      out.write("\r\n");
      out.write("            <li><a href=\"javascript:window.parent.jianyi2('xitong/thirdPartyApply.jsp','加盟申请')\">加盟申请</a></li>\r\n");
      out.write("            ");

                }
                if (current_flags.contains("6006")) {
            
      out.write("\r\n");
      out.write("            <li><a href=\"javascript:window.parent.jianyi2('xitong/guanliyuan.jsp','后台管理员管理')\">后台管理员管理</a></li>\r\n");
      out.write("            ");

                }
                if (current_flags.contains("6003")) {
            
      out.write("\r\n");
      out.write("            <li><a href=\"javascript:window.parent.jianyi2('xitong/userfeedback.jsp','用户反馈')\">用户反馈</a></li>\r\n");
      out.write("            ");

                }
                if (current_flags.contains("6008")) {
            
      out.write("\r\n");
      out.write("            <li><a href=\"javascript:window.parent.jianyi2('xitong/tuisong.jsp','会员推送')\">会员推送</a></li>\r\n");
      out.write("            ");
}
      out.write("\r\n");
      out.write("            <li><a href=\"javascript:window.parent.jianyi2('xitong/password_edit.jsp','修改密码')\">修改密码</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("    $(document).ready(\r\n");
      out.write("            function () {\r\n");
      out.write("                var leftarr = ['yonghu', 'order', 'jianshenfang', 'xinxi', 'xitong', 'faxian'];\r\n");
      out.write("                var nowhref = window.location.href;\r\n");
      out.write("                for (l in leftarr) {\r\n");
      out.write("                    if (nowhref.indexOf(leftarr[l]) > -1) {\r\n");
      out.write("                        $(\"#\" + leftarr[l]).show();\r\n");
      out.write("                    } else {\r\n");
      out.write("                        $(\"#\" + leftarr[l]).hide();\r\n");
      out.write("                    }\r\n");
      out.write("                }\r\n");
      out.write("            });\r\n");
      out.write("</script>");
      out.write("<!--End Sidebar-->\r\n");
      out.write("<div class=\"iframe_box\">\r\n");
      out.write("    <div class=\"box_input\">\r\n");
      out.write("        <form id=\"form1\" name=\"form1\" method=\"post\" action=\"news_edit.jsp\">\r\n");
      out.write("            <input name=\"id\" id=\"id\" type=\"hidden\" value=\"");
      out.print(id);
      out.write("\"/>\r\n");
      out.write("            <input name=\"action\" id=\"action\" type=\"hidden\" value=\"");
      out.print(action);
      out.write("\"/>\r\n");
      out.write("            <input name=\"newstype\" id=\"newstype\" type=\"hidden\" value=\"1\"/>\r\n");
      out.write("            <ul class=\"row2 clearfix\">\r\n");
      out.write("                <li>\r\n");
      out.write("                    <label for=\"textfield\">栏&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;目：</label>\r\n");
      out.write("                    <select name=\"newsclass\" id=\"newsclass\">\r\n");
      out.write("                        <option value=\"0\">选择栏目</option>\r\n");
      out.write("\r\n");
      out.write("                        ");

                            List clist = utildb.Get_List("id,classname,parentid", "hy_news_class", "where idtype=0 and isdel=0 and parentid=0", "");
                            if (clist != null) {
                                for (Iterator its = clist.listIterator(); its.hasNext(); ) {
                                    Doc docx = (Doc) its.next();
                                    if (newsclass == docx.getIn("id")) {
                                        out.println("<option value=\"" + docx.get("id") + "\" selected>&nbsp;|└" + docx.get("classname") + "</option>");
                                    } else {
                                        out.println("<option value=\"" + docx.get("id") + "\">├" + docx.get("classname") + "</option>");
                                    }
                                    List plist = utildb.Get_List("id,classname", "hy_news_class", "where isdel=0 and parentid=" + docx.getIn("id") + "", "");
                                    if (clist != null) {
                                        for (Iterator pits = plist.listIterator(); pits.hasNext(); ) {
                                            Doc docp = (Doc) pits.next();
                                            if (newsclass == docp.getIn("id")) {
                                                out.println("<option value=\"" + docp.get("id") + "\" selected>&nbsp;|└" + docp.get("classname") + "</option>");
                                            } else {
                                                out.println("<option value=\"" + docp.get("id") + "\">&nbsp;|└" + docp.get("classname") + "</option>");
                                            }

                                        }
                                    }
                                }
                            }
                        
      out.write("\r\n");
      out.write("                    </select>\r\n");
      out.write("\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>排序：<input type=\"text\" name=\"ordernum\" id=\"ordernum\" value=\"");
      out.print(ordernum );
      out.write("\" style=\"width:50px;\"/>从大到小\r\n");
      out.write("                </li>\r\n");
      out.write("\r\n");
      out.write("            </ul>\r\n");
      out.write("            <ul class=\"row1 clearfix\">\r\n");
      out.write("                <li>\r\n");
      out.write("                    <label for=\"textfield\">标&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;题：</label>\r\n");
      out.write("                    <input type=\"text\" name=\"newstitle\" id=\"newstitle\" value=\"");
      out.print(newstitle );
      out.write("\" style=\"width:300px;\"/>\r\n");
      out.write("                </li>\r\n");
      out.write("                ");
      out.write("\r\n");
      out.write("                <li>\r\n");
      out.write("                    <label for=\"textfield\">关键字：</label>\r\n");
      out.write("                    <input type=\"text\" name=\"keywords\" id=\"keywords\" value=\"");
      out.print(keywords );
      out.write("\" style=\"width:300px;\"/>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <label for=\"textfield\">跳转地址：</label>\r\n");
      out.write("                    <input type=\"text\" name=\"urladdress\" id=\"urladdress\" value=\"");
      out.print(urladdress );
      out.write("\" style=\"width:300px;\"/>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    <label for=\"textfield\">针对渠道号：</label>\r\n");
      out.write("                    <input type=\"text\" name=\"bossname\" id=\"bossname\" value=\"");
      out.print(bossname );
      out.write("\" style=\"width:300px;\"/>\r\n");
      out.write("                </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("            <ul class=\"row1 clearfix\">\r\n");
      out.write("                <li>标识图片：\r\n");
      out.write("                    标识小图片：\r\n");
      out.write("    <span class=\"input\"><span class=\"upload_file\"><div>\r\n");
      out.write("        <div class=\"up_input\">\r\n");
      out.write("            <input name=\"FileUpload\" id=\"smallfileUpload\" type=\"file\"/>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"tips\">\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"clear\"></div>\r\n");
      out.write("        <input type=\"hidden\" name=\"smallfile\" value=\"");
      out.print(smallfile);
      out.write("\"/>\r\n");
      out.write("    </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"img\" id=\"smallfileDetail\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t</span>\r\n");
      out.write("                </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("            <ul class=\"row1 clearfix\">\r\n");
      out.write("                <li>\r\n");
      out.write("                    标识大图片：\r\n");
      out.write("    <span class=\"input\"><span class=\"upload_file\"><div>\r\n");
      out.write("        <div class=\"up_input\">\r\n");
      out.write("            <input name=\"FileUpload\" id=\"bigfileUpload\" type=\"file\"/>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"tips\">\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"clear\"></div>\r\n");
      out.write("        <input type=\"hidden\" name=\"bigfile\" value=\"");
      out.print(bigfile);
      out.write("\"/>\r\n");
      out.write("    </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"img\" id=\"bigfileDetail\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("\t\t\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\t\t</span>\r\n");
      out.write("\r\n");
      out.write("                </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("            <script>\r\n");
      out.write("                if ($('#smallfileUpload').size()) {\r\n");
      out.write("                    global_obj.file_upload($('#smallfileUpload'), $('#form1 input[name=smallfile]'), $('#smallfileDetail'), 'web_column');\r\n");
      out.write("                    $('#smallfileDetail').html(global_obj.img_link($('#form1 input[name=smallfile]').val()));\r\n");
      out.write("                    if ($('#form1 input[name=smallfile]').val() != '') {\r\n");
      out.write("                        $('#smallfileDetail').append('<div class=\"del\">删除</div>');\r\n");
      out.write("                    }\r\n");
      out.write("                    $('#smallfileDetail div').click(function () {\r\n");
      out.write("                        $('#form1 input[name=smallfile]').val('');\r\n");
      out.write("                        $(this).parent().html('');\r\n");
      out.write("                    });\r\n");
      out.write("                }\r\n");
      out.write("                if ($('#bigfileUpload').size()) {\r\n");
      out.write("                    global_obj.file_upload($('#bigfileUpload'), $('#form1 input[name=bigfile]'), $('#bigfileDetail'), 'web_column', '', '', '', '', '', 200);\r\n");
      out.write("                    $('#bigfileDetail').html(global_obj.img_linkheight($('#form1 input[name=bigfile]').val()), '200');\r\n");
      out.write("                    if ($('#form1 input[name=bigfile]').val() != '') {\r\n");
      out.write("                        $('#bigfileDetail').append('<div class=\"del\">删除</div>');\r\n");
      out.write("                    }\r\n");
      out.write("                    $('#bigfileDetail div').click(function () {\r\n");
      out.write("                        $('#form1 input[name=bigfile]').val('');\r\n");
      out.write("                        $(this).parent().html('');\r\n");
      out.write("                    });\r\n");
      out.write("                }\r\n");
      out.write("            </script>\r\n");
      out.write("            <ul class=\"row1 clearfix\">\r\n");
      out.write("                <li><label for=\"textfield\">描述：</label>\r\n");
      out.write("                    <textarea id=\"classnavicontent\" name=\"classnavicontent\" rows=\"3\"\r\n");
      out.write("                              cols=\"100\">");
      out.print(classnavicontent);
      out.write("</textarea>\r\n");
      out.write("                </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("            <ul class=\"row1 clearfix\">\r\n");
      out.write("                <li>\r\n");
      out.write("                    <script type=\"text/plain\" id=\"contents\" name=\"contents\" class=\"ckeditor\">\r\n");
      out.write("                        ");
      out.print(content );
      out.write("\r\n");
      out.write("                    </script>\r\n");
      out.write("                    <script type=\"text/javascript\">var editor = new baidu.editor.ui.Editor(edit_options);\r\n");
      out.write("                    editor.render(\"contents\");\r\n");
      out.write("                    </script>\r\n");
      out.write("                </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("            <div class=\"row_btn\">\r\n");
      out.write("                <button type=\"button\" class=\"btn_formA\" onclick=\"usersave()\" name=\"tjbutton\" id=\"tjbutton\">确定保存</button>\r\n");
      out.write("                <span id=\"tisspan\"></span>\r\n");
      out.write("            </div>\r\n");
      out.write("        </form>\r\n");
      out.write("    </div>\r\n");
      out.write("</div><!--r_iframe END-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div style=\"display:none\"></div>");
      out.write("<!--End Sidebar-->\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
