/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.28
 * Generated at: 2016-01-09 02:14:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.share3.coach_005fshare;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.baje.sz.ajax.LogUtility;
import com.hanyou.util.BasicType;
import com.baje.sz.util.DateUtil;
import com.baje.sz.ajax.AjaxDate;
import com.baje.sz.ajax.AjaxXml;
import com.baje.sz.util.Doc;
import com.baje.sz.util.Selectic;
import com.baje.sz.util.RequestUtil;
import java.util.*;

public final class share_005fpaiban_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.baje.sz.ajax.AjaxXml");
    _jspx_imports_classes.add("com.baje.sz.util.DateUtil");
    _jspx_imports_classes.add("com.baje.sz.ajax.AjaxDate");
    _jspx_imports_classes.add("com.hanyou.util.BasicType");
    _jspx_imports_classes.add("com.baje.sz.util.Selectic");
    _jspx_imports_classes.add("com.baje.sz.util.Doc");
    _jspx_imports_classes.add("com.baje.sz.util.RequestUtil");
    _jspx_imports_classes.add("com.baje.sz.ajax.LogUtility");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n");
      out.write("<meta http-equiv=\"Content-type\" name=\"viewport\" content=\"initial-scale=1.0, maximum-scale=1.0, user-scalable=no, width=device-width\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, user-scalable=0, minimum-scale=1.0, maximum-scale=1.0\">\r\n");
      out.write("<title>教练分享</title>\r\n");
      out.write("<!-- Mobile Devices Support @begin -->\r\n");
      out.write("    <meta content=\"application/xhtml+xml;charset=UTF-8\" http-equiv=\"Content-Type\">\r\n");
      out.write("    <meta content=\"no-cache,must-revalidate\" http-equiv=\"Cache-Control\">\r\n");
      out.write("    <meta content=\"no-cache\" http-equiv=\"pragma\">\r\n");
      out.write("    <meta content=\"0\" http-equiv=\"expires\">\r\n");
      out.write("    <meta content=\"telephone=no, address=no\" name=\"format-detection\">\r\n");
      out.write("    <meta name=\"apple-mobile-web-app-capable\" content=\"yes\" /> <!-- apple devices fullscreen -->\r\n");
      out.write("    <meta name=\"apple-mobile-web-app-status-bar-style\" content=\"black-translucent\" />\r\n");
      out.write("<!-- Mobile Devices Support @end --> \r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\t/* CSS Document */\r\n");
      out.write("\t*{margin:0;padding:0}\r\n");
      out.write("\thtml{overflow-x:auto}\r\n");
      out.write("\tbody{width:100%; min-height:100%; background:#f5f5f5; -webkit-user-select:none;-webkit-user-drag:none;-webkit-text-size-adjust:none; line-height:1.5em;}\r\n");
      out.write("\tbody, input, textarea, select { font-size: 14px; color: #333; font-family: \"microsoft yahei\", Arial, Helvetica, sans-serif; }\r\n");
      out.write("\timg{ width:100%; border:none;}\r\n");
      out.write("\tbutton{ border:0;background:transparent;font-family:'microsoft yahei','Helvetica Neue',Helvetica,Arial,sans-serif;font-size:16px}\r\n");
      out.write("\tinput,button{-webkit-tap-highlight-color:rgba(255,255,255,0)}\r\n");
      out.write("\tli,ul{list-style:none;}\r\n");
      out.write("\ta { color: #9f3192; text-decoration: none; }\r\n");
      out.write("\ta:hover { color: #333; text-decoration: none; }\r\n");
      out.write("\ta img { border: 0;}\r\n");
      out.write("\t.fl { float: left !important; }\r\n");
      out.write("\t.fr { float: right !important; }\r\n");
      out.write("\t.clear{ clear:both;}\r\n");
      out.write("\t.f_weight{ font-weight:bold;}\r\n");
      out.write("\t.text_c{ text-align:center;}\r\n");
      out.write("\t.text_r{ text-align:right;}\r\n");
      out.write("\t.text_l{ text-align:left;}\r\n");
      out.write("\t.ysh_webkit { display: -webkit-box; -webkit-box-orient: horizontal; }\r\n");
      out.write("\t.ysh_webkit_flex{ -webkit-box-flex: 1; -webkit-box-align: center;}\r\n");
      out.write("\t.title { background:#d33e37; padding:15px; color:#fff;}\r\n");
      out.write("\t.title_img { width:88px; height:88px; border-radius:88px; -moz-border-radius:88px; -webkit-border-radius:88px; margin:0 auto; border:5px solid #c83b34;}\r\n");
      out.write("\t.title_img img {border-radius:88px; -moz-border-radius:88px; -webkit-border-radius:88px;}\r\n");
      out.write("\t.title_con h3 { font-size:18px; font-weight:bold; margin-top:3px; line-height:2em; text-align:center;}\r\n");
      out.write("\t.title_con p { font-size:14px; line-height:2em; text-align:center;} \r\n");
      out.write("\t.title_con span { margin:0 20px; }\r\n");
      out.write("\t.color_gray { color:#999;}\r\n");
      out.write("\t.color_red { color:#d33e37;}\r\n");
      out.write("\t.content { background:#fff; margin-bottom:15px;}\r\n");
      out.write("\t.con_table { font-size:14px;}\r\n");
      out.write("\t.con_table th { font-weight:normal; font-size:18px; border-bottom:1px solid #eee; padding:5px;}\r\n");
      out.write("\t.con_table em { font-size:10px; color:#999; text-align:center;  font-style:normal;}\r\n");
      out.write("\t.color_red em { color:#d33e37;}\r\n");
      out.write("\t.con_table td { padding:10px 5px; border-right:1px solid #eee; border-bottom:1px solid #eee;}\r\n");
      out.write("\t.bg_gray { background:#f7f7f7; color:#999; font-size:12px; text-align:center;}\r\n");
      out.write("\t.con_t { height:24px; line-height:24px;font-size:16px; margin-bottom:10px; padding:15px 15px 0;}\r\n");
      out.write("\t.con_c { padding:15px;font-size:14px; color:#999; border-top:1px solid #eee;}\r\n");
      out.write("\t.con_c i {display:inline-block; margin-right:15px; padding:5px 10px; height:18px; line-height:18px;border:1px solid #ddd; -moz-border-radius:5px;-webkit-border-radius:5px; border-radius:5px; font-style:normal;}\r\n");
      out.write("\t/*浮动层*/\r\n");
      out.write("\t.h70 { height:70px;}\r\n");
      out.write("\t.footer { position:fixed; z-index:999; bottom:0px; left:0px; width:100%;color:#fff; line-height:18px; *zoom:1;  filter:alpha(Opacity=70);  background: rgba(0, 0, 0, 0.7) !important; -moz-opacity:0.7;-khtml-opacity: 0.7; }\r\n");
      out.write("\t.footer .logo{ max-height:44px; max-width:44px; margin:8px 10px;}\r\n");
      out.write("\t.footer .l_title { margin-left:20px;  margin:12px 0; font-size:12px;}\r\n");
      out.write("\t.footer .l_title h3 { font-weight:bold; font-size:18px; margin-bottom:5px; color:#d33e37;}\r\n");
      out.write("\t.footer .botton_download { width:100px; text-align:center; margin:12px; height:36px; color:#fff;  background:#d33e37; border-radius:5px; line-height:36px; font-size:16px;}\r\n");
      out.write("\t.footer .botton_download:hover { background:#c33932; border-radius:5px; cursor:pointer;}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");

	RequestUtil ru=new RequestUtil(request);
	int coach_id=ru.getInt("coach_id");
	Selectic utidb=new Selectic();
	AjaxDate ajaxDate=new AjaxDate();
	Doc coachDoc=utidb.Get_Doc("coach_headpic,specialty,coach_sex,coach_name,coach_birth","hy_coach","where id=?","mysqlss",new Object[]{coach_id});
	if(coachDoc==null||coachDoc.isEmpty()){
		out.print("教练不存在</body></html>");
		return;
	}
	int coach_age=0;
	if(coachDoc.getIn("coach_birth")>0){
		coach_age=Integer.parseInt(AjaxXml.Get_Date("now","YY04"))-Integer.parseInt(AjaxXml.timeStamp2Date(coachDoc.getIn("coach_birth"), "YY04"));
	}
	String first_Day=ajaxDate.getFirstDayOfWeek("now",1);//该周第一天
	String last_Day=ajaxDate.DateAdd("d",7,first_Day);
	DateUtil du=new DateUtil();
	List<Doc> isBookList=utidb.Get_List(" id,book_time,book_status", "hy_member_book_coach","where coach_id=? and book_time>=?"
            + "  and book_time<? and book_status!=2 and book_status!=3 and isdel=0","mysqlss",new Object[]{coach_id,AjaxXml.getTimestamp(first_Day),AjaxXml.getTimestamp(last_Day)});
	System.out.print(isBookList);

      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"content\">\r\n");
      out.write("    <div class=\"title\">\r\n");
      out.write("        <div class=\"title_img\"><img src=\"");
      out.print(coachDoc.get("coach_headpic")!=null&&!"".equals(coachDoc.get("coach_headpic"))?coachDoc.get("coach_headpic"):"images/user.png");
      out.write("\"></div>\r\n");
      out.write("        <div class=\"title_con\">\r\n");
      out.write("          <h3>");
      out.print(coachDoc.get("coach_name","") );
      out.write("</h3>\r\n");
      out.write("          <p>");
      out.print(coachDoc.getIn("coach_sex")==2?"女":"男" );
      out.write("<span>|</span>");
      out.print(coach_age);
      out.write("岁</p>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\t<div class=\"con_table\">\r\n");
      out.write("    <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("      <tr>\r\n");
      out.write("        <th class=\"color_gray\">");
      out.print(AjaxXml.Get_Date("now","MM"));
      out.write("月</th>\r\n");
      out.write("        ");
	
        	String date_array[]=new String[7];
        	for(int i=0;i<=6;i++){
        			String date=ajaxDate.DateAdd("d",i,first_Day);
        			date_array[i]=date;
        			du.set(date);
        			if(AjaxXml.Get_Date("now","YY04-MM-DD").equals(date)){
        				
      out.write("\r\n");
      out.write("        \t\t\t\t <th class=\"color_red\">");
      out.print(AjaxXml.Get_Date(date,"DD"));
      out.write("<br><em>周");
      out.print(du.getWeekday());
      out.write("</em></th>\r\n");
      out.write("        \t\t\t\t");

        			}else{
        				
      out.write("\r\n");
      out.write("        \t\t\t\t <th>");
      out.print(AjaxXml.Get_Date(date,"DD"));
      out.write("<br><em>周");
      out.print(du.getWeekday());
      out.write("</em></th>\r\n");
      out.write("        \t\t\t\t");

        			}
        	}
        
      out.write("\r\n");
      out.write("      </tr>\r\n");
      out.write("     ");

     	for(int i=8;i<=21;i++){
     		
      out.write("\r\n");
      out.write("     \t\t <tr>\r\n");
      out.write("\t\t        <td>");
      out.print(BasicType.getCoachBookTime(i));
      out.write("</td>\r\n");
      out.write("\t\t        ");

		        for(int s=0;s<date_array.length;s++){
		        	String add="<td>&nbsp;</td>";
		        	if(isBookList!=null){
		        		for(Doc doc:isBookList){
		        			System.out.print(AjaxXml.timeStamp2Date(doc.getIn("book_time"),"YY04-MM-DD HH:00")+" ---- "+AjaxXml.Get_Date(date_array[s],"YY04-MM-DD")+" "+BasicType.getCoachBookTime(i));
		        			if(AjaxXml.timeStamp2Date(doc.getIn("book_time"),"YY04-MM-DD HH:00").equals(AjaxXml.Get_Date(date_array[s],"YY04-MM-DD")+" "+BasicType.getCoachBookTime(i))){
		        				add="<td class=\"bg_gray\">已预约</td>";
		        			}
		        		}
		        	}
		        	out.print(add);
		        } 
      out.write("\r\n");
      out.write("    \t  </tr>\r\n");
      out.write("     \t\t");

     	}
     
      out.write("\r\n");
      out.write("    </table>\r\n");
      out.write(" </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"content\">\r\n");
      out.write("    <div class=\"con_t\">智能健身房介绍</div>\r\n");
      out.write("    <div class=\"con_c\">\r\n");
      out.write("    \t<p>健身运动是时尚健康生活的标志与印记，更是一种强调品质的生活态度。\r\n");
      out.write("它强健体魄、雕塑体形、释放压力，更唤醒每个人内心对美的渴望与追求！</p>\r\n");
      out.write("\t    <p>超能健身房，凭借强大实力与专业支持，带动健身领域的时尚潮流，为会员带来身心投入的全新运动感受！</p>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"h70\"></div>\r\n");
      out.write("<div class=\"footer ysh_webkit\"> \r\n");
      out.write("        <div class=\"logo\"><img src=\"images/logo.png\"> </div>\t\r\n");
      out.write("        <div class=\"l_title ysh_webkit_flex\">\r\n");
      out.write("            <h3>智能教练</h3>\r\n");
      out.write("            <p>您的智能健身顾问</p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"botton_download\" onclick=\"window.open('/down/coach_index.html','_self');\">立即下载</div>\t \r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
