/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.28
 * Generated at: 2015-12-30 02:12:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.manage;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.baje.sz.util.*;
import com.baje.sz.ajax.*;
import com.hanyou.admin.sys.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/manage/ini_sys.jsp", Long.valueOf(1448868343606L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("com.hanyou.admin.sys");
    _jspx_imports_packages.add("com.baje.sz.ajax");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("com.baje.sz.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

    request.setCharacterEncoding("utf-8");
    AdminLogin checklogin = new AdminLogin();
    int userid = 0;
    String user_name = "guest";
    String current_flags = "";
    int gym_group_id = 0, gym_id = 0;
    Selectic utildb = new Selectic();
    Doc currentUser = null;
    int ii = checklogin.checkLogin(request, response);
    if (ii == 0) {
        user_name = checklogin.getuser_name();
        userid = checklogin.getuserid();

        currentUser = utildb.Get_Doc("user_flag,gym_group_id,gym_id", "hy_sys_user", "where id=" + userid, "mysqlss");
        //System.out.println("currentUser="+currentUser);
        if (currentUser != null) {
            current_flags = AjaxXml.getString(currentUser.get("user_flag"));
            //System.out.println("current_flags="+current_flags);
            gym_group_id = currentUser.getIn("gym_group_id");
            gym_id = currentUser.getIn("gym_id");

        }
        //flag=admin_username.get("flag");
    } else {
        out.print("<script>");
        out.print("alert('请登录后再操作');");
        out.print("window.parent.location = '/manage/login.jsp'");
        out.print("</script>");
        return;
    }

      out.write('\r');
      out.write('\n');

    response.setHeader("Pragma", "No-cache");
    response.setHeader("Cache-Control", "no-cache");
    response.setDateHeader("Expires", 0);
    String ifrurl = "main.jsp";
    String ifrstr = "首页";

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\"/>\r\n");
      out.write("    <meta name=\"robots\" content=\"noarchive\"/>\r\n");
      out.write("    <title>健身房</title>\r\n");
      out.write("    <base target=\"_self\"/>\r\n");
      out.write("    <link href=\"css/reset.css\" rel=\"stylesheet\" type=\"text/css\"/>\r\n");
      out.write("    <link href=\"css/base.css\" rel=\"stylesheet\" type=\"text/css\"/>\r\n");
      out.write("    <link href=\"css/colortemplate.css\" rel=\"stylesheet\" type=\"text/css\"/>\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\"\r\n");
      out.write("          href=\"js/themes/default/easyui.css\"/>\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"js/themes/icon.css\"/>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"js/jquery-1.7.2.min.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"js/jquery.easyui.min.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"js/main.js\"></script>\r\n");
      out.write("    <script language=\"javascript\" src='js/sys.js'></script>\r\n");
      out.write("    <script type=\"text/javascript\"\r\n");
      out.write("            src=\"js/artDialog4.1.6/artDialog.js?skin=green\"></script>\r\n");
      out.write("    <script type=\"text/javascript\"\r\n");
      out.write("            src=\"js/artDialog4.1.6/plugins/iframeTools.source.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("        var timeout = 500;\r\n");
      out.write("        var closetimer = 0;\r\n");
      out.write("        var ddmenuitem = 0;\r\n");
      out.write("\r\n");
      out.write("        function jsddm_open() {\r\n");
      out.write("            jsddm_canceltimer();\r\n");
      out.write("            jsddm_close();\r\n");
      out.write("            var pop_x = $(this).position().left;\r\n");
      out.write("            ddmenuitem = $(this).find('ul').eq(0).css({\r\n");
      out.write("                'visibility': 'visible',\r\n");
      out.write("                'left': pop_x\r\n");
      out.write("            });\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        function jsddm_close() {\r\n");
      out.write("            if (ddmenuitem)\r\n");
      out.write("                ddmenuitem.css('visibility', 'hidden');\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        function jsddm_timer() {\r\n");
      out.write("            closetimer = window.setTimeout(jsddm_close, timeout)\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        function jsddm_canceltimer() {\r\n");
      out.write("            if (closetimer) {\r\n");
      out.write("                window.clearTimeout(closetimer);\r\n");
      out.write("                closetimer = null;\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        $(document).ready(function () {\r\n");
      out.write("            $('#jsddm > li').bind('mouseover', jsddm_open);\r\n");
      out.write("            $('#jsddm > li').bind('mouseout', jsddm_timer);\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        document.onclick = jsddm_close;\r\n");
      out.write("    </script>\r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("        function jianyi3(urls, titles) {\r\n");
      out.write("            var tab = $(\"#tabsN\").tabs('getSelected');\r\n");
      out.write("            if ($('#tabsN').tabs('exists', titles)) {\r\n");
      out.write("                $('#tt')\r\n");
      out.write("                        .tabs(\r\n");
      out.write("                                'add',\r\n");
      out.write("                                {\r\n");
      out.write("                                    title: 'titles ',\r\n");
      out.write("                                    content: '<iframe style=\"border-top-width: 0px; border-left-width: 0px;'\r\n");
      out.write("                                    + ' border-bottom-width: 0px;  border-right-width: 0px\"'\r\n");
      out.write("                                    + ' src=\"'\r\n");
      out.write("                                    + urls\r\n");
      out.write("                                    + '\" frameborder=\"0\" width=\"100%\" scrolling=\"yes\" height=\"100%\"></iframe>',\r\n");
      out.write("                                    closable: true\r\n");
      out.write("                                });\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("        function jianyi2(urls, titles) {\r\n");
      out.write("            var chk = true;\r\n");
      out.write("            var tab = $('#tabsN').tabs('getSelected');\r\n");
      out.write("            if ($('#tabsN').tabs('exists', titles)) {\r\n");
      out.write("                $('#tabsN').tabs('select', titles);\r\n");
      out.write("                tab = $('#tabsN').tabs('getSelected');\r\n");
      out.write("                $('#tabsN')\r\n");
      out.write("                        .tabs(\r\n");
      out.write("                                'update',\r\n");
      out.write("                                {\r\n");
      out.write("                                    tab: tab,\r\n");
      out.write("                                    options: {\r\n");
      out.write("                                        content: '<iframe src=\"'\r\n");
      out.write("                                        + urls\r\n");
      out.write("                                        + '\" frameborder=\"0\" width=\"100%\" scrolling=\"auto\" height=\"100%\"></iframe>'\r\n");
      out.write("                                    }\r\n");
      out.write("                                });\r\n");
      out.write("\r\n");
      out.write("            } else {\r\n");
      out.write("                $('#tabsN')\r\n");
      out.write("                        .tabs(\r\n");
      out.write("                                'add',\r\n");
      out.write("                                {\r\n");
      out.write("                                    title: titles,\r\n");
      out.write("                                    closed: true,\r\n");
      out.write("                                    border: false,\r\n");
      out.write("                                    content: '<iframe src=\"'\r\n");
      out.write("                                    + urls\r\n");
      out.write("                                    + '\" frameborder=\"0\" width=\"100%\" scrolling=\"auto\" height=\"100%\"></iframe>',\r\n");
      out.write("                                    closable: true\r\n");
      out.write("\r\n");
      out.write("                                });\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("        function tabclose(titles) {\r\n");
      out.write("            $('#tabsN').tabs('close', titles);\r\n");
      out.write("        }\r\n");
      out.write("        //设备入库\r\n");
      out.write("        function deviceEdit(id, title) {\r\n");
      out.write("            openurl('shebei/device_library_edit.jsp?id=' + id + '', 'shezhi',\r\n");
      out.write("                    title, 700, 380, 0, 20, true);\r\n");
      out.write("        }\r\n");
      out.write("    </script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body style=\"\" scroll=no>\r\n");
      out.write("<div id=\"container\">\r\n");
      out.write("\r\n");
      out.write("    <div class=\"header\">\r\n");
      out.write("        <h1>健身房管理系统</h1>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"nav_click\">\r\n");
      out.write("            <div class=\"nc_left\"></div>\r\n");
      out.write("            <!--left down-->\r\n");
      out.write("\r\n");
      out.write("            <ul class=\"nc_cont\" id=\"jsddm\">\r\n");
      out.write("\t\t\t\t");

					if(gym_group_id==0){
				
      out.write("\r\n");
      out.write("\t\t\t\t<li class=\"ncc_01\"><a href=\"javascript:jianyi2('yonghu/yonghu.jsp','用户管理')\">用户管理</a>\r\n");
      out.write("                    <ul class=\"nav_list\">\r\n");
      out.write("                        ");

                            if (current_flags.contains("1001")) {
                        
      out.write("\r\n");
      out.write("                        <li><a href=\"javascript:window.parent.jianyi2('yonghu/yonghu.jsp','用户管理')\">用户管理</a></li>\r\n");
      out.write("                        ");

                            }
                            if (current_flags.contains("1004")) {
                        
      out.write("\r\n");
      out.write("                        <li><a href=\"javascript:window.parent.jianyi2('yonghu/level_experience_group.jsp?group_type=1','积分操作组别')\">积分操作组别</a></li>\r\n");
      out.write("                        ");

                            }
                            if (current_flags.contains("1005")) {
                        
      out.write("\r\n");
      out.write("                        <li><a href=\"javascript:window.parent.jianyi2('yonghu/level_experience_operating.jsp?operating_type=1','积分操作')\">积分操作</a></li>\r\n");
      out.write("                        ");

                            }
                            if (current_flags.contains("1007")) {
                        
      out.write("\r\n");
      out.write("                        <li><a href=\"javascript:window.parent.jianyi2('yonghu/level_experience_operating_user.jsp?operating_type=1','积分获取情况')\">积分获取情况</a></li>\r\n");
      out.write("                        ");
} 
      out.write("\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("\t\t\t\t");

					}
				
      out.write("\r\n");
      out.write("                <li class=\"ncc_01\"><a href=\"javascript:jianyi2('order/hy_order.jsp','订单管理')\">订单管理</a>\r\n");
      out.write("                    <ul class=\"nav_list\">\r\n");
      out.write("                        ");
if (current_flags.contains("2007")) { 
      out.write("\r\n");
      out.write("                        <li><a href=\"javascript:window.parent.jianyi2('order/hy_order.jsp','订单管理')\">订单管理</a></li>\r\n");
      out.write("                        ");

                            }
                        if(gym_group_id==0){
                        	if(current_flags.contains("2025")){
                        		
      out.write("\r\n");
      out.write("                        \t\t<li><a href=\"javascript:window.parent.jianyi2('order/member_measure_item.jsp','体测项目')\">体测项目</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        \t\t");
                       		
                        	}
                            if (current_flags.contains("2026")) {
                        
      out.write("\r\n");
      out.write("                        <li><a href=\"javascript:window.parent.jianyi2('order/plan_action_type.jsp','动作类型')\">动作类型</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        ");

                            }
                            if (current_flags.contains("2027")) {
                        
      out.write("\r\n");
      out.write("                        <li><a href=\"javascript:window.parent.jianyi2('order/default_action.jsp','默认动作')\">默认动作</a></li>\r\n");
      out.write("                        ");

                            }
                            if (current_flags.contains("2028")) {
                        
      out.write("\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"javascript:window.parent.jianyi2('order/plan_action_type.jsp?type=1','健身目标')\">健身目标</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        ");
} if (current_flags.contains("2029")) {
                            
      out.write("\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"javascript:window.parent.jianyi2('order/common_language_class.jsp?','常用语类型')\">常用语类型</a>\r\n");
      out.write("                            </li>");
}
                            if(current_flags.contains("2030")){
                        	
      out.write("\r\n");
      out.write("                        \t <li>\r\n");
      out.write("                            \t<a href=\"javascript:window.parent.jianyi2('order/common_language.jsp','常用语设置')\">常用语设置</a>\r\n");
      out.write("                        \t</li>\r\n");
      out.write("                        \t");

                        	
                       		 }
                            if(current_flags.contains("2031")){
                        	
      out.write("\r\n");
      out.write("                        \t<li><a href=\"javascript:window.parent.jianyi2('order/pro_class.jsp?class_status=1','商品栏目')\">商品栏目</a></li>\r\n");
      out.write("                        \t");

                       		 }
                        }
                            if(current_flags.contains("2032")){
                        	
      out.write("\r\n");
      out.write("                        \t <li><a href=\"javascript:window.parent.jianyi2('order/pro_product.jsp','商品管理')\">商品管理</a></li>\r\n");
      out.write("                        \t");

                        }
                            if(gym_group_id==0){
	                            if(current_flags.contains("2033")){
	                        	
      out.write("\r\n");
      out.write("\t                       \t<li><a href=\"javascript:window.parent.jianyi2('order/user_money.jsp','用户资金记录')\">用户资金记录</a></li>\r\n");
      out.write("\t                       \t");

	                       		}
	                        }
      out.write("\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("                ");

                    if (gym_id == 0) {
                        out.print("<li class=\"ncc_02\"><a href=\"javascript:jianyi2('jianshenfang/gym.jsp','健身房管理')\">健身房管理</a>");
                    } else {
                        out.print("<li class=\"ncc_02\"><a href=\"javascript:jianyi2('jianshenfang/coach.jsp','教练管理')\">教练管理</a>");
                    }
                
      out.write("\r\n");
      out.write("\r\n");
      out.write("                <ul class=\"nav_list\">\r\n");
      out.write("                    ");

                        if (gym_group_id == 0) {
                            if (current_flags.contains("3001")) {
                    
      out.write("\r\n");
      out.write("                    <li><a href=\"javascript:window.parent.jianyi2('jianshenfang/jituan.jsp','连锁集团管理')\">连锁集团管理</a></li>\r\n");
      out.write("                    ");

                            }
                        }
                    if(gym_id==0){
                        if (current_flags.contains("3005")) {
                    
      out.write("\r\n");
      out.write("                    <li><a href=\"javascript:window.parent.jianyi2('jianshenfang/gym.jsp','健身房管理')\">健身房管理</a></li>\r\n");
      out.write("                    ");

                        }
                    }
                        if (current_flags.contains("3009")) {
                    
      out.write("\r\n");
      out.write("                    <li><a href=\"javascript:window.parent.jianyi2('jianshenfang/coach.jsp','教练管理')\">教练管理</a></li>\r\n");
      out.write("                    ");
} 
					if(current_flags.contains("3045")){ 
      out.write("\r\n");
      out.write("                    <li><a href=\"javascript:window.parent.jianyi2('jianshenfang/device.jsp','设备管理')\">设备管理</a></li>\r\n");
      out.write("                    ");

                        }
                        if (current_flags.contains("3049")) {
                    
      out.write("\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"javascript:window.parent.jianyi2('jianshenfang/bodyMeasure_titai.jsp', '体态管理')\">体态管理</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    ");

                        } 
                        if(current_flags.contains("3050")){
                        	
      out.write("\r\n");
      out.write("                        \t <li>\r\n");
      out.write("                        <a href=\"javascript:window.parent.jianyi2('jianshenfang/bodyMeasure_tineng.jsp', '体能管理')\">体能管理</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                        \t");

                        }
                        if(current_flags.contains("3051")){
                     		
      out.write("\r\n");
      out.write("                     \t\t  <li><a href=\"javascript:window.parent.jianyi2('jianshenfang/bodyMeasure_tice.jsp', '体测管理')\">体测管理</a>\r\n");
      out.write("                   \t\t\t\t </li>\r\n");
      out.write("                     \t\t");

                        }
                        if (current_flags.contains("3017")) {
                    
      out.write("\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <a href=\"javascript:window.parent.jianyi2('jianshenfang/gym_member_book.jsp?book_type=1','预约私教')\">预约私教</a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    ");
 
                        }
                    
      out.write("\r\n");
      out.write("                </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("                ");

                if(gym_group_id==0){
                    if (current_flags.contains("4004")) {
                
      out.write("\r\n");
      out.write("                <li class=\"ncc_03\"><a\r\n");
      out.write("                        href=\"javascript:window.parent.jianyi2('xinxi/news.jsp','信息内容')\">信息内容</a>\r\n");
      out.write("                    <ul class=\"nav_list\">\r\n");
      out.write("                        ");
 if (current_flags.contains("4001")) {
      out.write("\r\n");
      out.write("                        <li><a href=\"javascript:window.parent.jianyi2('xinxi/newsclass.jsp','信息内容')\">信息栏目</a></li>\r\n");
      out.write("                        ");

                            }
                            if (current_flags.contains("4002")) {
                        
      out.write("\r\n");
      out.write("                        <li><a href=\"javascript:window.parent.jianyi2('xinxi/news.jsp','信息栏目')\">信息内容</a></li>\r\n");
      out.write("\r\n");
      out.write("                        ");

                            }
                            if (current_flags.contains("4003")) {
                        
      out.write("\r\n");
      out.write("                        <li><a href=\"javascript:window.parent.jianyi2('xinxi/news_edit.jsp','发布信息')\">发布信息</a></li>\r\n");
      out.write("                        ");

                            }
                        
      out.write("\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("                ");

                    }
                }
                
      out.write("\r\n");
      out.write("                ");

                	if(gym_group_id==0){
                
      out.write("\r\n");
      out.write("                <li class=\"ncc_04\"><a href=\"javascript:window.parent.jianyi2('faxian/wenzhang.jsp','发现文章')\">发现文章</a>\r\n");
      out.write("                    <ul class=\"nav_list\">\r\n");
      out.write("                        ");
 if (current_flags.contains("5001")) {
                        
      out.write("\r\n");
      out.write("                        <li><a href=\"javascript:window.parent.jianyi2('faxian/wenzhang.jsp','发现文章')\">发现文章</a></li>\r\n");
      out.write("                        ");

                            }
                            if (current_flags.contains("5005")) {
                        
      out.write("\r\n");
      out.write("                        <li><a href=\"javascript:window.parent.jianyi2('faxian/huifu.jsp','文章评论')\">文章评论</a></li>\r\n");
      out.write("                        ");

                            }
                            if (current_flags.contains("5007")) {
                        
      out.write("\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"javascript:window.parent.jianyi2('faxian/hy_friendster_carousel.jsp','每日推荐')\">每日推荐</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        ");
} 
      out.write("\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("                ");

                	}
                
      out.write("\r\n");
      out.write("              ");

              if(gym_group_id==0){
              
      out.write("\r\n");
      out.write("               <li class=\"ncc_06\"><a href=\"javascript:jianyi2('xitong/rizhi.jsp','系统管理')\">系统管理</a>\r\n");
      out.write("              ");

              }else{
            	  
      out.write("\r\n");
      out.write("\t\t\t\t <li class=\"ncc_06\"><a href=\"javascript:jianyi2('xitong/password_edit.jsp','修改密码')\">修改密码</a>\r\n");
      out.write("            \t  ");

              }
              
      out.write("\r\n");
      out.write("                    <ul class=\"nav_list\">\r\n");
      out.write("                        ");

                     if(gym_group_id==0){
                        if (current_flags.contains("6001")) { 
      out.write("\r\n");
      out.write("                        <li><a href=\"javascript:window.parent.jianyi2('xitong/rizhi.jsp','系统日志')\">系统日志</a></li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <a href=\"javascript:window.parent.jianyi2('xitong/rizhi.jsp?log_type=2','教练系统日志')\">教练系统日志</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        ");

                            }
                            if (current_flags.contains("6002")) {
                        
      out.write("\r\n");
      out.write("                        <li><a href=\"javascript:window.parent.jianyi2('xitong/keyword.jsp','关键词管理')\">关键词管理</a></li>\r\n");
      out.write("                        ");

                            }
                            if (current_flags.contains("6009")) {
                        
      out.write("\r\n");
      out.write("                        <li><a href=\"javascript:window.parent.jianyi2('xitong/thirdPartyApply.jsp','加盟申请')\">加盟申请</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        ");

                            }
                            if (current_flags.contains("6006")) {
                        
      out.write("\r\n");
      out.write("                        <li><a href=\"javascript:window.parent.jianyi2('xitong/guanliyuan.jsp','后台管理员管理')\">后台管理员管理</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        ");

                            }
                            if (current_flags.contains("6003")) {
                        
      out.write("\r\n");
      out.write("                        <li><a href=\"javascript:window.parent.jianyi2('xitong/userfeedback.jsp','用户反馈')\">用户反馈</a></li>\r\n");
      out.write("                        ");

                            }
                            if (current_flags.contains("6008")) {
                        
      out.write("\r\n");
      out.write("                        <li><a href=\"javascript:window.parent.jianyi2('xitong/tuisong.jsp','会员推送')\">会员推送</a></li>\r\n");
      out.write("                        ");

                        }
                     }
                        
      out.write("\r\n");
      out.write("                        <li><a href=\"javascript:window.parent.jianyi2('xitong/password_edit.jsp','修改密码')\">修改密码</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </li>\r\n");
      out.write("\r\n");
      out.write("            </ul>\r\n");
      out.write("            <div class=\"c_right\"></div>\r\n");
      out.write("            <!--right down-->\r\n");
      out.write("        </div>\r\n");
      out.write("        <span class=\"right_exit\">操作员：");
      out.print(user_name);
      out.write(" | <a href=\"login.jsp?action=logout\" class=\"quit\">退出</a></span>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!--End Header-->\r\n");
      out.write("    <div class=\"easyui-tabs\" fit=\"true\" border=\"false\" id=\"tabsN\">\r\n");
      out.write("        <div title=\"");
      out.print(ifrstr);
      out.write("\">\r\n");
      out.write("            <iframe src=\"");
      out.print(ifrurl);
      out.write("\" frameborder=\"0\" id=\"iframeid\" width=\"100%\" height=\"100%\"></iframe>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<!--End Container-->\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
