/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.28
 * Generated at: 2015-11-30 07:27:55 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.manage;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.baje.sz.util.RequestUtil;
import com.hanyou.admin.sys.AdminLogin;
import net.sf.json.JSONObject;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.hanyou.admin.sys.AdminLogin");
    _jspx_imports_classes.add("com.baje.sz.util.RequestUtil");
    _jspx_imports_classes.add("net.sf.json.JSONObject");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

    response.setHeader("Pragma", "No-cache");
    response.setHeader("Cache-Control", "no-cache");
    response.setDateHeader("Expires", 0);
    RequestUtil ru = new RequestUtil(request);
    String action = ru.getString("action");
    if (action.equals("denglu")) {
        AdminLogin login = new AdminLogin();
        JSONObject result = login.checkAdminLogin(request, response);
        out.print(result.toString().trim());
        return;
    }
    if (action.equals("logout")) {
        AdminLogin login = new AdminLogin();
        login.logout(request, response);
        response.sendRedirect("login.jsp");
        return;
    }

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\"/>\r\n");
      out.write("    <title>健身房登录页面</title>\r\n");
      out.write("    <link href=\"css/logincss.css\" type=\"text/css\" rel=\"stylesheet\"/>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"js/jquery-1.7.2.min.js\"></script>\r\n");
      out.write("    <link type=\"text/css\" rel=\"stylesheet\" href=\"css/jquery.alert.css\"/>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"js/jquery.alert.js\"></script>\r\n");
      out.write("    <script language=javascript src='js/sys.js'></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"js/artDialog4.1.6/artDialog.js?skin=green\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"js/artDialog4.1.6/plugins/iframeTools.source.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("        function denglu_check() { //\r\n");
      out.write("            var user_name = $(\"#user_name\").val();\r\n");
      out.write("            var user_pwd = $(\"#user_pwd\").val();\r\n");
      out.write("            if (user_name == \"\" || user_name == \"请输入后台帐号\") {\r\n");
      out.write("                alert(\"请输入后台帐号\");\r\n");
      out.write("                return;\r\n");
      out.write("            }\r\n");
      out.write("            $(\"#tipsspan\").html(\"<img src='images/loading.gif' />加载中……请稍候……\");\r\n");
      out.write("            $.ajax({ //admin_login.jsp?action=denglu\r\n");
      out.write("                dataType: \"json\",\r\n");
      out.write("                type: \"post\", //post\r\n");
      out.write("                url: \"login.jsp\", //\r\n");
      out.write("                data: \"action=denglu&user_name=\" + user_name + \"&user_pwd=\" + user_pwd + \"\", //\r\n");
      out.write("                success: function (msg) {\r\n");
      out.write("                    if (msg.type == true) {\r\n");
      out.write("                        window.location.href = \"index.jsp\";\r\n");
      out.write("                    } else {\r\n");
      out.write("                        alert(msg.msg);\r\n");
      out.write("                        $(\"#tipsspan\").html(\"\");\r\n");
      out.write("                    }\r\n");
      out.write("                }\r\n");
      out.write("            });\r\n");
      out.write("        }\r\n");
      out.write("        function inputonclick(obj, NowClass) {\r\n");
      out.write("            document.getElementById(obj).className = NowClass;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        function SetFocus() {\r\n");
      out.write("            if (document.Login.username.value == \"\") {\r\n");
      out.write("                document.Login.username.focus();\r\n");
      out.write("            } else {\r\n");
      out.write("                document.Login.username.select();\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("    </script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"header\">\r\n");
      out.write("    <div class=\"header-warp\">\r\n");
      out.write("        <div class=\"logo\"><img src=\"images/logo.png\" width=\"198\"/></div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"wrapper\">\r\n");
      out.write("    <div class=\"title\">健身房后台管理</div>\r\n");
      out.write("    <div class=\"line\"></div>\r\n");
      out.write("    <div class=\"content\">\r\n");
      out.write("        <div class=\"text\">用户名</div>\r\n");
      out.write("        <input type=\"text\" name=\"user_name\" id=\"user_name\" class=\"input_txt\" value=\"\"/>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"text\">密码</div>\r\n");
      out.write("        <input type=\"password\" class=\"input_txt\" name=\"user_pwd\" id=\"user_pwd\"\r\n");
      out.write("               onkeydown=\"if(event.keyCode==13){denglu_check();}\"/>\r\n");
      out.write("        <span id=\"tipsspan\"></span>\r\n");
      out.write("        <input type=\"button\" id=\"denglu\" name=\"denglu\" value=\" 登 录 \" class=\"submit\" onclick=\"denglu_check()\"/>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"footer\"><a href=\"#\" title=\"U康官网\" target=\"_blank\">健身房官网</a> Copyright&copy;2010 – 2015 v1.0.1</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
