/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.28
 * Generated at: 2015-12-25 05:58:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.manage;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import net.sf.json.JSONObject;
import com.baje.sz.util.*;
import com.baje.sz.ajax.*;
import com.hanyou.admin.sys.*;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/manage/ini_sys.jsp", Long.valueOf(1448868343606L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("com.hanyou.admin.sys");
    _jspx_imports_packages.add("com.baje.sz.ajax");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("com.baje.sz.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("net.sf.json.JSONObject");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

    request.setCharacterEncoding("utf-8");
    AdminLogin checklogin = new AdminLogin();
    int userid = 0;
    String user_name = "guest";
    String current_flags = "";
    int gym_group_id = 0, gym_id = 0;
    Selectic utildb = new Selectic();
    Doc currentUser = null;
    int ii = checklogin.checkLogin(request, response);
    if (ii == 0) {
        user_name = checklogin.getuser_name();
        userid = checklogin.getuserid();

        currentUser = utildb.Get_Doc("user_flag,gym_group_id,gym_id", "hy_sys_user", "where id=" + userid, "mysqlss");
        //System.out.println("currentUser="+currentUser);
        if (currentUser != null) {
            current_flags = AjaxXml.getString(currentUser.get("user_flag"));
            //System.out.println("current_flags="+current_flags);
            gym_group_id = currentUser.getIn("gym_group_id");
            gym_id = currentUser.getIn("gym_id");

        }
        //flag=admin_username.get("flag");
    } else {
        out.print("<script>");
        out.print("alert('请登录后再操作');");
        out.print("window.parent.location = '/manage/login.jsp'");
        out.print("</script>");
        return;
    }

      out.write('\r');
      out.write('\n');


    JSONObject result =new AdminLogin().getMainInfo(gym_group_id,gym_id);


      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\"/>\r\n");
      out.write("    <meta name=\"robots\" content=\"noarchive\"/>\r\n");
      out.write("    <title>健身房管理系统</title>\r\n");
      out.write("\r\n");
      out.write("    <base target=\"_self\"/>\r\n");
      out.write("    <link href=\"css/reset.css\" rel=\"stylesheet\" type=\"text/css\"/>\r\n");
      out.write("    <link href=\"css/base.css\" rel=\"stylesheet\" type=\"text/css\"/>\r\n");
      out.write("    <link href=\"css/colortemplate.css\" rel=\"stylesheet\" type=\"text/css\"/>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"js/jquery-1.7.2.min.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"js/jquery.easyui.min.js\"></script>\r\n");
      out.write("    <script language=\"javascript\" src='js/sys.js'></script>\r\n");
      out.write("    <link type=\"text/css\" rel=\"stylesheet\" href=\"css/jquery.alert.css\"/>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"js/jquery.alert.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"js/artDialog4.1.6/artDialog.js?skin=green\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"js/artDialog4.1.6/plugins/iframeTools.source.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("        function tiaozhuan(type) {\r\n");
      out.write("            var loupan_id = $(\"#loupan_id\").val();\r\n");
      out.write("            $.ajax({\r\n");
      out.write("                cache: false,\r\n");
      out.write("                async: false,\r\n");
      out.write("                type: \"post\",\r\n");
      out.write("                url: \"ajax/loupan.jsp\",\r\n");
      out.write("                data: \"action=addLCookies&loupan_id=\" + loupan_id + \"\",\r\n");
      out.write("                success: function (msg) {\r\n");
      out.write("                },\r\n");
      out.write("                error: function () {\r\n");
      out.write("                }\r\n");
      out.write("            });\r\n");
      out.write("            window.location.href = \"kuaijie.jsp?loupan_id=\" + loupan_id + \"\";\r\n");
      out.write("        }\r\n");
      out.write("        function clicknum(opt) {\r\n");
      out.write("            if (opt == \"用户管理\") {\r\n");
      out.write("                window.parent.jianyi2('yonghu/yonghu.jsp', '用户管理');\r\n");
      out.write("            } else if (opt == \"当前订单\") {\r\n");
      out.write("                window.parent.jianyi2('yonghu/dingdan.jsp', '当前订单');\r\n");
      out.write("            } else if (opt == \"发布产品\") {\r\n");
      out.write("                window.parent.jianyi2('xinxi/shop.jsp', '发布产品');\r\n");
      out.write("            } else if (opt == \"妙圈管理\") {\r\n");
      out.write("                window.parent.jianyi2('quanzi/quanzi.jsp', '妙圈管理');\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("        function readNew(id, str) {\r\n");
      out.write("            openurl('xitong/news_read.jsp?id=' + id + '', 'xitong', str, 950, 380, 0, 10, true);\r\n");
      out.write("        }\r\n");
      out.write("        $(function () {\r\n");
      out.write("            $(\"#gonggao\").fadeOut(30000);\r\n");
      out.write("        });//公告显示\r\n");
      out.write("        function hid() {\r\n");
      out.write("            $(\"#gonggao\").hide();\r\n");
      out.write("        }\r\n");
      out.write("    </script>\r\n");
      out.write("\r\n");
      out.write("    <style type=\"text/css\">\r\n");
      out.write("        .panel-body {\r\n");
      out.write("            overflow-x: hidden;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .tabs-header {\r\n");
      out.write("            background: #8ebf6e;\r\n");
      out.write("            border-top: 1px #c3deb1 solid;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .tabs {\r\n");
      out.write("            border-bottom: 1px #5ca02e solid;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .tabs li.tabs-selected {\r\n");
      out.write("            -moz-border-bottom-colors: none;\r\n");
      out.write("            -moz-border-image: none;\r\n");
      out.write("            -moz-border-left-colors: none;\r\n");
      out.write("            -moz-border-right-colors: none;\r\n");
      out.write("            -moz-border-top-colors: none;\r\n");
      out.write("            border-color: #5ca02e #5ca02e #fff;\r\n");
      out.write("            border-style: solid;\r\n");
      out.write("            border-width: 1px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .tabs li {\r\n");
      out.write("            border: 1px solid #5ca02e;\r\n");
      out.write("            border-radius: 5px 5px 0 0;\r\n");
      out.write("            display: inline-block;\r\n");
      out.write("            float: left;\r\n");
      out.write("            margin-bottom: -1px;\r\n");
      out.write("            margin-right: 4px;\r\n");
      out.write("            padding: 0;\r\n");
      out.write("            position: relative;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .tabs li a.tabs-inner {\r\n");
      out.write("            background: url(\"images/tabs_enabled.png\") repeat-x scroll left top transparent;\r\n");
      out.write("            border-radius: 5px 5px 0 0;\r\n");
      out.write("            color: #476c2e;\r\n");
      out.write("            display: inline-block;\r\n");
      out.write("            height: 25px;\r\n");
      out.write("            line-height: 25px;\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            padding: 0 10px;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            white-space: nowrap;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .tabs li a.tabs-inner:hover {\r\n");
      out.write("            background: url(\"images/tabs_selected.png\") repeat-x scroll left top transparent;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .tabs li.tabs-selected a.tabs-inner {\r\n");
      out.write("            background: url(\"images/tabs_selected.png\") repeat-x scroll left bottom;\r\n");
      out.write("            color: #476c2e;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .tabs li a.tabs-close {\r\n");
      out.write("            background: url(\"images/tabs_close.gif\") no-repeat scroll 2px 2px transparent;\r\n");
      out.write("            display: block;\r\n");
      out.write("            font-size: 1px;\r\n");
      out.write("            height: 11px;\r\n");
      out.write("            opacity: 0.6;\r\n");
      out.write("            padding: 0;\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            right: 5px;\r\n");
      out.write("            top: 7px;\r\n");
      out.write("            width: 11px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .tabs li a.tabs-close:hover {\r\n");
      out.write("            background: url(\"images/tabs_closeB.gif\") no-repeat scroll 2px 2px transparent;\r\n");
      out.write("            background-color: #F90;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body class=\"ifr\">\r\n");
      out.write("<div class=\"full_box\">\r\n");
      out.write("    <div class=\"kj_nav\">\r\n");
      out.write("        <div class=\"kj_leftbox\">\r\n");
      out.write("            <div class=\"k_l_mt\">快捷菜单通道</div>\r\n");
      out.write("            <div class=\"k_l_mc\">\r\n");
      out.write("                <ul class=\"k_l_menu clearfix\">\r\n");
      out.write("                    <li>\r\n");
      out.write("                        <button class=\"btn_kjmenu\" type=\"button\" onclick=\"clicknum('用户管理')\">用户管理</button>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <!--li><button class=\"btn_kjmenu\" type=\"button\" onclick=\"clicknum('当前订单')\">当前订单</button></li>\r\n");
      out.write("                    <li><button class=\"btn_kjmenu\" type=\"button\" onclick=\"clicknum('发布产品')\">发布产品</button></li>\r\n");
      out.write("                    <li><button class=\"btn_kjmenu\" type=\"button\" onclick=\"clicknum('妙圈管理')\">妙圈管理</button></li -->\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div><!--kj_nav e-->\r\n");
      out.write("\r\n");
      out.write("    <div class=\"kj_main\">\r\n");
      out.write("      ");

      	if(gym_group_id==0){
      
      out.write("\r\n");
      out.write("        <div class=\"kj_tabs_title\">\r\n");
      out.write("            <ul class=\"clearfix\">\r\n");
      out.write("                <li><strong>用户数据信息</strong></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"kj_tabs_cont\">\r\n");
      out.write("            <div class=\"k_r_mc\">\r\n");
      out.write("                <ul class=\"kl_form clearfix\">\r\n");
      out.write("                    <li><span class=\"k_f_text\">当前用户数量：<b class=\"red\">");
      out.print(result.optInt("memNum") );
      out.write("\r\n");
      out.write("                    </b></span><a href=\"javascript:window.parent.jianyi2('yonghu/yonghu.jsp','用户管理')\">查看</a></li>\r\n");
      out.write("                    <li><span class=\"k_f_text\">今日新增：<b class=\"red\">");
      out.print(result.optInt("memNum_totday") );
      out.write("\r\n");
      out.write("                    </b></span></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      \r\n");
      out.write("      ");

      }
      
      out.write("\r\n");
      out.write("        <div class=\"kj_tabs_title\">\r\n");
      out.write("            <ul class=\"clearfix\">\r\n");
      out.write("                <li><strong>健身房数据信息</strong></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"kj_tabs_cont\">\r\n");
      out.write("            <div class=\"k_r_mc\">\r\n");
      out.write("                <ul class=\"kl_form clearfix\">\r\n");
      out.write("                 <li><span class=\"k_f_text\">总预约数量：<b class=\"red\">");
      out.print(result.optInt("book_num") );
      out.write("\r\n");
      out.write("                    </b></span><a href=\"javascript:window.parent.jianyi2('jianshenfang/gym_member_book.jsp','预约私教')\">查看</a></li>\r\n");
      out.write("                    <li><span class=\"k_f_text\">今日新增：<b class=\"red\">");
      out.print(result.optInt("book_num_today") );
      out.write("\r\n");
      out.write("                    </b></span></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("         <div class=\"kj_tabs_title\">\r\n");
      out.write("            <ul class=\"clearfix\">\r\n");
      out.write("                <li><strong>微信数据信息</strong></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"kj_tabs_cont\">\r\n");
      out.write("            <div class=\"k_r_mc\">\r\n");
      out.write("                <ul class=\"kl_form clearfix\">\r\n");
      out.write("                 <li><span class=\"k_f_text\">总订单数量：<b class=\"red\">");
      out.print(result.optInt("weixin_order_num") );
      out.write("\r\n");
      out.write("                    </b></span><a href=\"javascript:window.parent.jianyi2('order/hy_order.jsp','订单管理')\">查看</a></li>\r\n");
      out.write("                     <li><span class=\"k_f_text\">购买私教：<b class=\"red\">");
      out.print(result.optInt("weixin_book_num") );
      out.write("\r\n");
      out.write("                    </b></span><a href=\"javascript:window.parent.jianyi2('order/hy_order.jsp?order_type=1','订单管理')\">查看</a></li>\r\n");
      out.write("                     <li><span class=\"k_f_text\">充值：<b class=\"red\">");
      out.print(result.optInt("weixin_chongzhi_num") );
      out.write("\r\n");
      out.write("                    </b></span><a href=\"javascript:window.parent.jianyi2('order/hy_order.jsp?order_type=3','订单管理')\">查看</a></li>\r\n");
      out.write("                     <li><span class=\"k_f_text\">团体课程：<b class=\"red\">");
      out.print(result.optInt("weixin_tuanti_num") );
      out.write("\r\n");
      out.write("                    </b></span><a href=\"javascript:window.parent.jianyi2('order/hy_order.jsp?order_type=2','订单管理')\">查看</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- div class=\"kj_tabs_title\" style=\"margin-top:10px\">\r\n");
      out.write("          <ul class=\"clearfix\">\r\n");
      out.write("          <li><strong>预约信息</strong></li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        </div -->\r\n");
      out.write("    </div><!--kj_main e-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
