/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.28
 * Generated at: 2015-12-25 09:37:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.manage.yonghu;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.net.URLEncoder;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import com.baje.sz.ajax.*;
import com.baje.sz.util.*;
import com.hanyou.admin.sys.*;
import java.net.URLDecoder;
import com.baje.sz.util.*;
import com.baje.sz.ajax.*;
import com.hanyou.admin.sys.*;

public final class yonghu_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/manage/yonghu/../end.jsp", Long.valueOf(1448868342872L));
    _jspx_dependants.put("/manage/yonghu/../ini_sys.jsp", Long.valueOf(1448868343606L));
    _jspx_dependants.put("/manage/yonghu/../left.jsp", Long.valueOf(1451029963556L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("com.hanyou.admin.sys");
    _jspx_imports_packages.add("com.baje.sz.ajax");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("com.baje.sz.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.ArrayList");
    _jspx_imports_classes.add("java.net.URLEncoder");
    _jspx_imports_classes.add("java.net.URLDecoder");
    _jspx_imports_classes.add("java.util.Iterator");
    _jspx_imports_classes.add("java.util.List");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

    request.setCharacterEncoding("utf-8");
    AdminLogin checklogin = new AdminLogin();
    int userid = 0;
    String user_name = "guest";
    String current_flags = "";
    int gym_group_id = 0, gym_id = 0;
    Selectic utildb = new Selectic();
    Doc currentUser = null;
    int ii = checklogin.checkLogin(request, response);
    if (ii == 0) {
        user_name = checklogin.getuser_name();
        userid = checklogin.getuserid();

        currentUser = utildb.Get_Doc("user_flag,gym_group_id,gym_id", "hy_sys_user", "where id=" + userid, "mysqlss");
        //System.out.println("currentUser="+currentUser);
        if (currentUser != null) {
            current_flags = AjaxXml.getString(currentUser.get("user_flag"));
            //System.out.println("current_flags="+current_flags);
            gym_group_id = currentUser.getIn("gym_group_id");
            gym_id = currentUser.getIn("gym_id");

        }
        //flag=admin_username.get("flag");
    } else {
        out.print("<script>");
        out.print("alert('请登录后再操作');");
        out.print("window.parent.location = '/manage/login.jsp'");
        out.print("</script>");
        return;
    }

      out.write('\r');
      out.write('\n');

    response.setHeader("Pragma", "No-cache");
    response.setHeader("Cache-Control", "no-cache");
    response.setDateHeader("Expires", 0);
    request.setCharacterEncoding("utf-8");
    if (current_flags.indexOf(",1001,") < 0) {
        response.sendRedirect("../error.jsp?left=yonghu");
        return;
    }
    UserMember um = new UserMember();
    RequestUtil ru = new RequestUtil(request);
    String action = ru.getString("action");
    if (action.equals("del")) {
        out.print(um.memDel(request, userid, user_name, gym_group_id, gym_id).toString());
        return;
    }
    if (action.equals("batchdel")) {
        out.print(um.memDelBatch(request, userid, user_name, gym_group_id, gym_id).toString());
        return;
    }
    int pages = ru.getInt("page");
    if (pages == 0) {
        pages = 1;
    }
    int pn = ru.getInt("pn");
    if (pn == 0) {
        pn = 20;
    }

    String mem_name = ru.getString("mem_name", "");
    String mem_username = ru.getString("mem_username", "");
    String mem_mobile = ru.getString("mem_mobile", "");
    int province_id = ru.getInt("province_id");
    int city_id = ru.getInt("city_id");
    int area_id = ru.getInt("area_id");


      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\"/>\r\n");
      out.write("    <title>table</title>\r\n");
      out.write("    <link href=\"../css/reset.css\" rel=\"stylesheet\" type=\"text/css\"/>\r\n");
      out.write("    <link href=\"../css/base.css\" rel=\"stylesheet\" type=\"text/css\"/>\r\n");
      out.write("    <link href=\"../css/page.css\" rel=\"stylesheet\" type=\"text/css\"/>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"../js/jquery-1.7.2.min.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"../js/artDialog4.1.6/artDialog.js?skin=green\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"../js/artDialog4.1.6/plugins/iframeTools.source.js\"></script>\r\n");
      out.write("    <script language=\"javascript\" src='../js/sys.js'></script>\r\n");
      out.write("    <script language=\"javascript\" src='/manage/js/webcalendar.js'></script>\r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("        function del(id) {\r\n");
      out.write("            art.dialog({\r\n");
      out.write("                id: 'delID',\r\n");
      out.write("                content: '是否确定删除选中项？',\r\n");
      out.write("                lock: true,\r\n");
      out.write("                button: [\r\n");
      out.write("                    {\r\n");
      out.write("                        name: '确定',\r\n");
      out.write("                        callback: function () {\r\n");
      out.write("                            if (id == \"\") {\r\n");
      out.write("                                art.dialog({id: 'delID'}).close();\r\n");
      out.write("                                art.dialog.alert('请选择操作项');\r\n");
      out.write("                                return false;\r\n");
      out.write("                            }\r\n");
      out.write("                            $.ajax({\r\n");
      out.write("                                beforeSend: function () {\r\n");
      out.write("                                    art.dialog({id: 'delID'}).close();\r\n");
      out.write("                                    art.dialog({\r\n");
      out.write("                                        id: 'tisID',\r\n");
      out.write("                                        lock: true,\r\n");
      out.write("                                        title: '提交中，请稍候……'\r\n");
      out.write("                                    });\r\n");
      out.write("                                },\r\n");
      out.write("                                dataType: \"json\",\r\n");
      out.write("                                type: \"post\",\r\n");
      out.write("                                url: \"yonghu.jsp\",\r\n");
      out.write("                                data: \"action=del&id=\" + id + \"\",\r\n");
      out.write("                                success: function (msg) {\r\n");
      out.write("                                    art.dialog({id: 'tisID'}).close();\r\n");
      out.write("                                    if (msg.type == true) {\r\n");
      out.write("                                        art.dialog({\r\n");
      out.write("                                            id: 'tisID',\r\n");
      out.write("                                            content: msg.msg,\r\n");
      out.write("                                            lock: true,\r\n");
      out.write("                                            icon: \"succeed\",\r\n");
      out.write("                                            cancelVal: '确定',\r\n");
      out.write("                                            cancel: function () {\r\n");
      out.write("                                                window.location.reload();\r\n");
      out.write("                                                art.dialog({id: \"tisID\"}).close();\r\n");
      out.write("                                            }\r\n");
      out.write("                                        });\r\n");
      out.write("                                    } else {\r\n");
      out.write("                                        art.dialog.alert(msg.msg);\r\n");
      out.write("                                    }\r\n");
      out.write("                                }\r\n");
      out.write("                            });\r\n");
      out.write("                            return false;\r\n");
      out.write("                        },\r\n");
      out.write("                        focus: true\r\n");
      out.write("                    },\r\n");
      out.write("                    {\r\n");
      out.write("                        name: '取消'\r\n");
      out.write("                    }\r\n");
      out.write("                ]\r\n");
      out.write("            });\r\n");
      out.write("        }\r\n");
      out.write("        function batchdel(id) {\r\n");
      out.write("            var ids = getcheckbox(\"id\");\r\n");
      out.write("            if (ids == \"\") {\r\n");
      out.write("                alert(\"请选择删除项？\");\r\n");
      out.write("                return;\r\n");
      out.write("            }\r\n");
      out.write("            art.dialog({\r\n");
      out.write("                id: 'delID',\r\n");
      out.write("                content: '是否确定删除选中项？',\r\n");
      out.write("                lock: true,\r\n");
      out.write("                button: [\r\n");
      out.write("                    {\r\n");
      out.write("                        name: '确定',\r\n");
      out.write("                        callback: function () {\r\n");
      out.write("                            $.ajax({\r\n");
      out.write("                                beforeSend: function () {\r\n");
      out.write("                                    art.dialog({id: 'delID'}).close();\r\n");
      out.write("                                    art.dialog({\r\n");
      out.write("                                        id: 'tisID',\r\n");
      out.write("                                        lock: true,\r\n");
      out.write("                                        title: '提交中，请稍候……'\r\n");
      out.write("                                    });\r\n");
      out.write("                                },\r\n");
      out.write("                                dataType: \"json\",\r\n");
      out.write("                                type: \"post\",\r\n");
      out.write("                                url: \"yonghu.jsp\",\r\n");
      out.write("                                data: \"action=batchdel&ids=\" + ids + \"\",\r\n");
      out.write("                                success: function (msg) {\r\n");
      out.write("                                    art.dialog({id: 'tisID'}).close();\r\n");
      out.write("                                    if (msg.type == true) {\r\n");
      out.write("                                        art.dialog({\r\n");
      out.write("                                            id: 'tisID',\r\n");
      out.write("                                            content: msg.msg,\r\n");
      out.write("                                            lock: true,\r\n");
      out.write("                                            icon: \"succeed\",\r\n");
      out.write("                                            cancelVal: '确定',\r\n");
      out.write("                                            cancel: function () {\r\n");
      out.write("                                                window.location.reload();\r\n");
      out.write("                                                art.dialog({id: \"tisID\"}).close();\r\n");
      out.write("                                            }\r\n");
      out.write("                                        });\r\n");
      out.write("                                    } else {\r\n");
      out.write("                                        art.dialog.alert(msg.msg);\r\n");
      out.write("                                    }\r\n");
      out.write("                                }\r\n");
      out.write("                            });\r\n");
      out.write("                            return false;\r\n");
      out.write("                        },\r\n");
      out.write("                        focus: true\r\n");
      out.write("                    },\r\n");
      out.write("                    {\r\n");
      out.write("                        name: '取消'\r\n");
      out.write("                    }\r\n");
      out.write("                ]\r\n");
      out.write("            });\r\n");
      out.write("        }\r\n");
      out.write("        function addyonghu(id, title) {\r\n");
      out.write("            openurl('yonghu_edit.jsp?id=' + id + '', 'user', title, 700, 380, 0, 10, true);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        function getCitys(object) {\r\n");
      out.write("            var provinceId = $(object).val();\r\n");
      out.write("            if (provinceId == 0) {\r\n");
      out.write("                return false;\r\n");
      out.write("            } else {\r\n");
      out.write("                $.ajax({\r\n");
      out.write("                    dataType: \"json\",\r\n");
      out.write("                    type: \"post\",\r\n");
      out.write("                    url: \"/manage/ajax/sysajax.jsp\",\r\n");
      out.write("                    data: \"action=getCitysOfProvince&provinceId= \" + provinceId + \" \",\r\n");
      out.write("                    success: function (backJson) {\r\n");
      out.write("                        if (backJson.type) {\r\n");
      out.write("                            var citys = backJson.dataJson;\r\n");
      out.write("                            $(\"#city\").empty();\r\n");
      out.write("                            $(\"#city\").append(\"<option value=\\\"0\\\">--所在城市--</option>\");\r\n");
      out.write("                            for (var i = 0; i < citys.length; i++) {\r\n");
      out.write("                                var option = $(\"<option value=\" + citys[i].cityId + \">\" + citys[i].city + \"</option>\");\r\n");
      out.write("                                $(\"#city\").append(option);\r\n");
      out.write("                            }\r\n");
      out.write("                        }\r\n");
      out.write("                    }\r\n");
      out.write("                });\r\n");
      out.write("\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("        function getAreas(object) {\r\n");
      out.write("            var city_id = $(object).val();\r\n");
      out.write("            if (city_id == 0) {\r\n");
      out.write("                return false;\r\n");
      out.write("            } else {\r\n");
      out.write("                $.ajax({\r\n");
      out.write("                    dataType: \"json\",\r\n");
      out.write("                    type: \"post\",\r\n");
      out.write("                    url: \"/manage/ajax/sysajax.jsp\",\r\n");
      out.write("                    data: \"action=getAreasOfCity&city_id= \" + city_id + \" \",\r\n");
      out.write("                    success: function (backJson) {\r\n");
      out.write("                        if (backJson.type) {\r\n");
      out.write("                            var areas = backJson.dataJson;\r\n");
      out.write("                            $(\"#areaId\").empty();\r\n");
      out.write("                            for (var i = 0; i < areas.length; i++) {\r\n");
      out.write("                                var option = $(\"<option value=\" + areas[i].areaId + \">\" + areas[i].area + \"</option>\");\r\n");
      out.write("                                $(\"#areaId\").append(option);\r\n");
      out.write("                            }\r\n");
      out.write("                        }\r\n");
      out.write("                    }\r\n");
      out.write("                });\r\n");
      out.write("\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    </script>\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"ifr\">\r\n");
      out.write("\r\n");
      out.write("<link href=\"/manage/css/colortemplate.css\" rel=\"stylesheet\" type=\"text/css\"/>\r\n");
      out.write("<div class=\"sidebarWrap\">\r\n");
      out.write("\t");

		if(gym_group_id==0){
	
      out.write("\r\n");
      out.write("\t    <div class=\"sidebar\" id=\"yonghu\" style=\"display:none\">\r\n");
      out.write("        <h3>\r\n");
      out.write("            <span>用户管理</span>\r\n");
      out.write("        </h3>\r\n");
      out.write("        <ul class=\"nav_list\">\r\n");
      out.write("\r\n");
      out.write("            ");

                if (current_flags.contains("1001")) {
            
      out.write("\r\n");
      out.write("            <li><a href=\"javascript:window.parent.jianyi2('yonghu/yonghu.jsp','用户管理')\">用户管理</a></li>\r\n");
      out.write("            ");

                }
                if (current_flags.contains("1004")) {
            
      out.write("\r\n");
      out.write("             <li><a href=\"javascript:window.parent.jianyi2('yonghu/level_experience_group.jsp?group_type=1','积分操作组别')\">积分操作组别</a></li>\r\n");
      out.write("            ");

                }
                if (current_flags.contains("1005")) {
            
      out.write("\r\n");
      out.write("           <li><a href=\"javascript:window.parent.jianyi2('yonghu/level_experience_operating.jsp?operating_type=1','积分操作')\">积分操作</a></li>\r\n");
      out.write("            ");

                }
                if (current_flags.contains("1007")) {
            
      out.write("\r\n");
      out.write("             <li><a href=\"javascript:window.parent.jianyi2('yonghu/level_experience_operating_user.jsp?operating_type=1','积分获取情况')\">积分获取情况</a></li>\r\n");
      out.write("            ");

                }
               
      out.write("\r\n");
      out.write("        </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("\t");

		}
	
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div class=\"sidebar\" id=\"jianshenfang\" style=\"display:none\">\r\n");
      out.write("        <h3>\r\n");
      out.write("            <span>健身房管理</span>\r\n");
      out.write("        </h3>\r\n");
      out.write("        <ul class=\"nav_list\">\r\n");
      out.write("            ");

                if (gym_group_id == 0) {
                    if (current_flags.contains("3001")) {
            
      out.write("\r\n");
      out.write("            <li><a href=\"javascript:window.parent.jianyi2('jianshenfang/jituan.jsp','连锁集团管理')\">连锁集团管理</a></li>\r\n");
      out.write("            ");

                    }
                }
						 if(gym_id==0){  
                if (current_flags.contains("3005")) {
            
      out.write("\r\n");
      out.write("            <li><a href=\"javascript:window.parent.jianyi2('jianshenfang/gym.jsp','健身房管理')\">健身房管理</a></li>\r\n");
      out.write("            ");

                }
					  	} 
                if (current_flags.contains("3009")) {
            
      out.write("\r\n");
      out.write("            <li><a href=\"javascript:window.parent.jianyi2('jianshenfang/coach.jsp','教练管理')\">教练管理</a></li>\r\n");
      out.write("            ");
}
				if (current_flags.contains("3045")) { 
				
      out.write("\r\n");
      out.write("            <li><a href=\"javascript:window.parent.jianyi2('jianshenfang/device.jsp','设备管理')\">设备管理</a></li>\r\n");
      out.write("            ");

                 }
                 if (current_flags.contains("3049")) {
             
      out.write("\r\n");
      out.write("             <li>\r\n");
      out.write("                 <a href=\"javascript:window.parent.jianyi2('jianshenfang/bodyMeasure_titai.jsp', '体态管理')\">体态管理</a>\r\n");
      out.write("             </li>\r\n");
      out.write("             ");

                 } 
                 if(current_flags.contains("3050")){
                 	
      out.write("\r\n");
      out.write("                 \t <li>\r\n");
      out.write("                 <a href=\"javascript:window.parent.jianyi2('jianshenfang/bodyMeasure_tineng.jsp', '体能管理')\">体能管理</a>\r\n");
      out.write("             </li>\r\n");
      out.write("                 \t");

                 }
                 if(current_flags.contains("3051")){
              		
      out.write("\r\n");
      out.write("              \t\t  <li><a href=\"javascript:window.parent.jianyi2('jianshenfang/bodyMeasure_tice.jsp', '体测管理')\">体测管理</a>\r\n");
      out.write("            \t\t\t\t </li>\r\n");
      out.write("              \t\t");

                 }
                if (current_flags.contains("3017")) {
            
      out.write("\r\n");
      out.write("            <li>\r\n");
      out.write("                <a href=\"javascript:window.parent.jianyi2('jianshenfang/gym_member_book.jsp?book_type=1','预约私教')\">预约私教</a>\r\n");
      out.write("            </li>\r\n");
      out.write("            ");
 
                }
            
      out.write("\r\n");
      out.write("        </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"sidebar\" id=\"order\" style=\"display:none\">\r\n");
      out.write("        <h3>\r\n");
      out.write("            <span>订单管理</span>\r\n");
      out.write("        </h3>\r\n");
      out.write("        <ul class=\"nav_list\">\r\n");
      out.write("            ");
if (current_flags.contains("2007")) { 
      out.write("\r\n");
      out.write("            <li><a href=\"javascript:window.parent.jianyi2('order/hy_order.jsp','订单管理')\">订单管理</a></li>\r\n");
      out.write("            ");

                }
            if(gym_group_id==0){
                if (current_flags.contains("2026")) {
            
      out.write("\r\n");
      out.write("            <li><a href=\"javascript:window.parent.jianyi2('order/plan_action_type.jsp','动作类型')\">动作类型</a></li>\r\n");
      out.write("            ");

                }
                if (current_flags.contains("2027")) {
            
      out.write("\r\n");
      out.write("            <li><a href=\"javascript:window.parent.jianyi2('order/default_action.jsp','默认动作')\">默认动作</a></li>\r\n");
      out.write("            ");

                }
                if (current_flags.contains("2028")) {
            
      out.write("\r\n");
      out.write("            <li><a href=\"javascript:window.parent.jianyi2('order/plan_action_type.jsp?type=1','健身目标')\">健身目标</a></li>\r\n");
      out.write("             ");
} if (current_flags.contains("2029")) {
                            
      out.write("\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"javascript:window.parent.jianyi2('order/common_language_class.jsp?','常用语类型')\">常用语类型</a>\r\n");
      out.write("                            </li>");

                } if(current_flags.contains("2030")){
                	
      out.write("\r\n");
      out.write("                \t <li>\r\n");
      out.write("                    \t<a href=\"javascript:window.parent.jianyi2('order/common_language.jsp','常用语设置')\">常用语设置</a>\r\n");
      out.write("                \t</li>\r\n");
      out.write("                \t");

                	
                } if(current_flags.contains("2031")){
                    	
      out.write("\r\n");
      out.write("                    \t<li><a href=\"javascript:window.parent.jianyi2('order/pro_class.jsp?class_status=1','商品栏目')\">商品栏目</a></li>\r\n");
      out.write("                    \t");

                    }
            }
                if(current_flags.contains("2032")){
                    	
      out.write("\r\n");
      out.write("                    \t <li><a href=\"javascript:window.parent.jianyi2('order/pro_product.jsp','商品管理')\">商品管理</a></li>\r\n");
      out.write("                    \t");

                    }
                if(gym_group_id==0){
	                if(current_flags.contains("2033")){
	                    	
      out.write("\r\n");
      out.write("\t                   \t<li><a href=\"javascript:window.parent.jianyi2('order/user_money.jsp','用户资金记录')\">用户资金记录</a></li>\r\n");
      out.write("\t                   \t");

	                   } 
	                }
	                   
      out.write("\r\n");
      out.write("             </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("    ");

    if(gym_group_id==0){
        if (current_flags.contains("4004")) {
    
      out.write("\r\n");
      out.write("    <div class=\"sidebar\" id=\"xinxi\" style=\"display:none\">\r\n");
      out.write("        <h3>\r\n");
      out.write("            <span>信息管理</span>\r\n");
      out.write("        </h3>\r\n");
      out.write("        <ul class=\"nav_list\">\r\n");
      out.write("            ");
 if (current_flags.contains("4002")) {
      out.write("\r\n");
      out.write("            <li><a href=\"javascript:window.parent.jianyi2('xinxi/news.jsp','信息内容')\">信息内容</a></li>\r\n");
      out.write("            ");

                }
                if (current_flags.contains("4001")) {
            
      out.write("\r\n");
      out.write("            <li><a href=\"javascript:window.parent.jianyi2('xinxi/newsclass.jsp','信息栏目')\">信息栏目</a></li>\r\n");
      out.write("\r\n");
      out.write("            ");

                }
                if (current_flags.contains("4003")) {
            
      out.write("\r\n");
      out.write("            <li><a href=\"javascript:window.parent.jianyi2('xinxi/news_edit.jsp','发布信息')\">发布信息</a></li>\r\n");
      out.write("            ");

                }
            
      out.write("\r\n");
      out.write("        </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("    ");

        }
    }
    
      out.write("\r\n");
      out.write("    ");

    	if(gym_group_id==0){
    
      out.write("\r\n");
      out.write("    <div class=\"sidebar\" id=\"faxian\" style=\"display:none\">\r\n");
      out.write("        <h3>\r\n");
      out.write("            <span>发现管理</span>\r\n");
      out.write("        </h3>\r\n");
      out.write("        <ul class=\"nav_list\">\r\n");
      out.write("            ");
 if (current_flags.contains("5001")) { 
      out.write("\r\n");
      out.write("            <li><a href=\"javascript:window.parent.jianyi2('faxian/wenzhang.jsp','发现文章')\">发现文章</a></li>\r\n");
      out.write("            ");

                }
                if (current_flags.contains("5005")) {
            
      out.write("\r\n");
      out.write("            <li><a href=\"javascript:window.parent.jianyi2('faxian/huifu.jsp','文章评论')\">文章评论</a></li>\r\n");
      out.write("            ");

                }
                if (current_flags.contains("5007")) {
            
      out.write("\r\n");
      out.write("            <li><a href=\"javascript:window.parent.jianyi2('faxian/hy_friendster_carousel.jsp','每日推荐')\">每日推荐</a></li>\r\n");
      out.write("            ");
} 
      out.write("\r\n");
      out.write("        </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("\t");

    	}
	
      out.write("\r\n");
      out.write("    <div class=\"sidebar\" id=\"xitong\" style=\"display:none\">\r\n");
      out.write("        <h3>\r\n");
      out.write("            <span>系统管理管理</span>\r\n");
      out.write("        </h3>\r\n");
      out.write("        <ul class=\"nav_list\">\r\n");
      out.write("            ");

          if(gym_group_id==0){
            if (current_flags.contains("6001")) { 
      out.write("\r\n");
      out.write("            <li><a href=\"javascript:window.parent.jianyi2('xitong/rizhi.jsp','系统日志')\">系统日志</a></li>\r\n");
      out.write("            <li><a href=\"javascript:window.parent.jianyi2('xitong/rizhi.jsp?log_type=2','教练系统日志')\">教练系统日志</a></li>\r\n");
      out.write("            ");

                }
                if (current_flags.contains("6002")) {
            
      out.write("\r\n");
      out.write("            <li><a href=\"javascript:window.parent.jianyi2('xitong/keyword.jsp','关键词管理')\">关键词管理</a></li>\r\n");
      out.write("            ");

                }
                if (current_flags.contains("6009")) {
            
      out.write("\r\n");
      out.write("            <li><a href=\"javascript:window.parent.jianyi2('xitong/thirdPartyApply.jsp','加盟申请')\">加盟申请</a></li>\r\n");
      out.write("            ");

                }
                if (current_flags.contains("6006")) {
            
      out.write("\r\n");
      out.write("            <li><a href=\"javascript:window.parent.jianyi2('xitong/guanliyuan.jsp','后台管理员管理')\">后台管理员管理</a></li>\r\n");
      out.write("            ");

                }
                if (current_flags.contains("6003")) {
            
      out.write("\r\n");
      out.write("            <li><a href=\"javascript:window.parent.jianyi2('xitong/userfeedback.jsp','用户反馈')\">用户反馈</a></li>\r\n");
      out.write("            ");

                }
                if (current_flags.contains("6008")) {
            
      out.write("\r\n");
      out.write("            <li><a href=\"javascript:window.parent.jianyi2('xitong/tuisong.jsp','会员推送')\">会员推送</a></li>\r\n");
      out.write("            ");

            }
          }
            
      out.write("\r\n");
      out.write("            <li><a href=\"javascript:window.parent.jianyi2('xitong/password_edit.jsp','修改密码')\">修改密码</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("    $(document).ready(\r\n");
      out.write("            function () {\r\n");
      out.write("                var leftarr = ['yonghu', 'order', 'jianshenfang', 'xinxi', 'xitong', 'faxian'];\r\n");
      out.write("                var nowhref = window.location.href;\r\n");
      out.write("                for (l in leftarr) {\r\n");
      out.write("                    if (nowhref.indexOf(leftarr[l]) > -1) {\r\n");
      out.write("                        $(\"#\" + leftarr[l]).show();\r\n");
      out.write("                    } else {\r\n");
      out.write("                        $(\"#\" + leftarr[l]).hide();\r\n");
      out.write("                    }\r\n");
      out.write("                }\r\n");
      out.write("            });\r\n");
      out.write("</script>");
      out.write("<!--End Sidebar-->\r\n");
      out.write("<div class=\"iframe_box\">\r\n");
      out.write("    <div class=\"form_info\"><strong>会员列表</strong></div>\r\n");
      out.write("    <div class=\"form_cont mb10\">\r\n");
      out.write("        <form id=\"form1\" name=\"form1\" method=\"get\" action=\"\">\r\n");
      out.write("            <ul class=\"row3\">\r\n");
      out.write("                <li>会员名称：<input name=\"mem_name\" type=\"text\" id=\"mem_name\" value=\"");
      out.print(mem_name);
      out.write("\" style=\"width:100px;\"/>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>会员账号：<input name=\"mem_username\" type=\"text\" id=\"mem_username\" value=\"");
      out.print(mem_username);
      out.write("\"\r\n");
      out.write("                                style=\"width:100px;\"/></li>\r\n");
      out.write("                <li>手机号码：<input name=\"mem_mobile\" type=\"text\" id=\"mem_mobile\" value=\"");
      out.print(mem_mobile);
      out.write("\"\r\n");
      out.write("                                style=\"width:100px;\"/></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("            <ul class=\"row3\" style=\"margin-top:3px;\">\r\n");
      out.write("                <li>所在省份：\r\n");
      out.write("                    <select name=\"province_id\" onchange=\"getCitys(this)\">\r\n");
      out.write("                        <option value=\"0\">--所在省份--</option>\r\n");
      out.write("                        ");

                            List<Doc> provinceList = utildb
                                    .Get_List("provinceid,province", "g_province",
                                            " where isdel=0 and country_id=41", "mysqlss");
                            if (provinceList != null) {
                                for (Doc doc : provinceList) {
                                    if (doc != null) {
                        
      out.write("\r\n");
      out.write("                        <option value=\"");
      out.print(doc.get("provinceid"));
      out.write("\"\r\n");
      out.write("                                ");

                                    if (province_id == doc.getIn("provinceid")) {
                                        out.print("selected=\"selected\"");
                                    }
                                
      out.write('>');
      out.print(doc.get("province"));
      out.write("\r\n");
      out.write("                        </option>\r\n");
      out.write("                        ");

                                    }
                                }
                            } else {
                                out.print("<option  value=\"0\">--所在省份--</option>");
                            }
                        
      out.write("\r\n");
      out.write("                    </select>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>所在城市：\r\n");
      out.write("                    ");

                        List<Doc> cityList = null;
                        if (province_id != 0) {
                            cityList = utildb.Get_List("cityid,city", "g_city", "where isdel=0 and province_id=" + province_id, "mysqlss");
                        }
                    
      out.write("\r\n");
      out.write("                    <select name=\"city_id\" id=\"city\" onchange=\"getAreas(this)\">\r\n");
      out.write("                        <option value=\"0\">--所在城市--</option>\r\n");
      out.write("                        ");

                            if (cityList != null) {
                                for (Doc doc : cityList) {
                                    if (doc != null) {
                        
      out.write("\r\n");
      out.write("                        <option value=\"");
      out.print(doc.get("cityid"));
      out.write('"');

                            if (city_id == doc.getIn("cityid")) {
                                out.print("selected=\"selected\"");
                            }
                        
      out.write(' ');
      out.write('>');
      out.print(doc.get("city"));
      out.write("\r\n");
      out.write("                        </option>\r\n");
      out.write("                        ");

                                    }
                                }
                            } else {
                                out.print("<option  value=\"0\">--所在城市--</option>");
                            }
                        
      out.write("\r\n");
      out.write("                    </select>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>所在区县:\r\n");
      out.write("                    ");

                        List<Doc> areaList = null;
                        if (city_id != 0) {
                            areaList = utildb.Get_List("areaid,area", "g_area", "where isdel=0 and city_id=" + city_id, "mysqlss");
                        }
                    
      out.write("\r\n");
      out.write("                    <select name=\"area_id\" id=\"areaId\">\r\n");
      out.write("                        <option value=\"0\">--所在区县--</option>\r\n");
      out.write("                        ");

                            if (areaList != null) {
                                for (Doc doc : areaList) {
                                    if (doc != null) {
                        
      out.write("\r\n");
      out.write("                        <option value=\"");
      out.print(doc.get("areaid"));
      out.write('"');

                            if (area_id == doc.getIn("areaid")) {
                                out.print("selected=\"selected\"");
                            }
                        
      out.write(' ');
      out.write('>');
      out.print(doc.get("area"));
      out.write("\r\n");
      out.write("                        </option>\r\n");
      out.write("                        ");

                                    }
                                }
                            } else {
                                out.print("<option  value=\"0\">--所在区县--</option>");
                            }
                        
      out.write("\r\n");
      out.write("                    </select>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                </li>\r\n");
      out.write("\r\n");
      out.write("                <li class=\"btn_line\" style=\"margin-top:3px;\">\r\n");
      out.write("                    <button type=\"button\" class=\"btn_formA\" onclick=\"$('#form1').submit()\">查&nbsp;&nbsp;询</button>\r\n");
      out.write("                </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("\r\n");
      out.write("        </form>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"btnitem mb10 clearfix\">\r\n");
      out.write("        <ul class=\"s_btn\">\r\n");
      out.write("            <li><a href=\"javascript:addyonghu(0,'新增用户')\">新增用户</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"form_table\">\r\n");
      out.write("        <form id=\"form2\" name=\"form2\" method=\"post\" action=\"\" autocomplete=\"off\">\r\n");
      out.write("            <table cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <th width=\"4%\">&nbsp;</th>\r\n");
      out.write("                    <th width=\"8%\">帐号</th>\r\n");
      out.write("                    <th width=\"8%\">姓名</th>\r\n");
      out.write("                    <th width=\"8%\">手机</th>\r\n");
      out.write("                    <th width=\"10%\">邮箱</th>\r\n");
      out.write("                    <th width=\"4%\">性别</th>\r\n");
      out.write("                    <th width=\"12%\">头像</th>\r\n");
      out.write("                    <th width=\"10%\">所在地区</th>\r\n");
      out.write("                    <th width=\"12%\">注册时间</th>\r\n");
      out.write("                    ");
      out.write("\r\n");
      out.write("                    <th width=\"7%\">操作</th>\r\n");
      out.write("                </tr>\r\n");
      out.write("                ");


                    String table = "hy_member a left join g_province b on a.mem_province=b.provinceid left join g_city c on a.mem_city=c.cityid left join g_area d on a.mem_area=d.areaid";
                    String wheres = "a.isdel=0 and a.is_coach=0";
                    List sqllist = new ArrayList();
                    if (!"".equals(mem_name)) {
                        wheres = wheres + " and a.mem_name like ?";
                        sqllist.add("%" + URLEncoder.encode(mem_name, "utf-8") + "%");
                    }
                    if (!mem_username.equals("")) {
                        wheres = wheres + " and a.mem_username like ?";
                        sqllist.add("%" + mem_username + "%");
                    }
                    if (!mem_mobile.equals("")) {
                        wheres = wheres + " and a.mem_mobile like ?";
                        sqllist.add("%" + mem_mobile + "%");
                    }
                    if (province_id > 0) {
                        wheres = wheres + " and a.mem_province=? ";
                        sqllist.add(province_id);
                    }
                    if (city_id > 0) {
                        wheres = wheres + " and a.mem_city=? ";
                        sqllist.add(city_id);
                    }
                    if (area_id > 0) {
                        wheres = wheres + " and a.mem_area=? ";
                        sqllist.add(area_id);
                    }
                    int i = 1;
                    String file = "a.id,a.mem_name,a.mem_username,a.mem_mobile,a.mem_headpic,a.mem_email,a.mem_weixin,b.province,c.city,d.area,a.mem_sex ," +
                            " a.mem_addtime,a.last_login_time,a.login_times ";
                    String order = " order by a.id desc";
                    String idd = "a.id";
                    i = pages * pn - pn + i;
                    String src = "";
                    int counts = utildb.Get_count(idd, table, wheres, "mysqlss", sqllist);
                    List list = utildb.Get_List(pages, pn, counts, table, wheres, file, order, "mysqlss", sqllist);
                    if (list != null) {
                        for (Iterator its = list.listIterator(); its.hasNext(); ) {
                            Doc doc = (Doc) its.next();
                
      out.write("\r\n");
      out.write("                <tr onmousemove=\"tableMove(this);\" onmouseout=\"tableOut(this)\">\r\n");
      out.write("                    <td><input name=\"id\" type=\"checkbox\" id=\"id\" value=\"");
      out.print(doc.get("id"));
      out.write("\"/></td>\r\n");
      out.write("                    <td>");
      out.print(doc.get("mem_username", ""));
      out.write("\r\n");
      out.write("                    </td>\r\n");
      out.write("                    <td>");
      out.print((doc.get("mem_name", "") != null) ? URLDecoder.decode(doc.get("mem_name"), "utf-8") : "");
      out.write("\r\n");
      out.write("                    </td>\r\n");
      out.write("                    <td>");
      out.print((doc.get("mem_mobile", "") != null) ? doc.get("mem_mobile") : "");
      out.write("\r\n");
      out.write("                    </td>\r\n");
      out.write("                    <td>");
      out.print((doc.get("mem_email", "") != null) ? doc.get("mem_email") : "");
      out.write("\r\n");
      out.write("                    </td>\r\n");
      out.write("                    <td>");

                        if (doc.getIn("mem_sex") == 1) {
                            out.print("男");
                        } else if (doc.getIn("mem_sex") == 2) {
                            out.print("女");
                        } else {
                            out.print("未设置");
                        }
                    
      out.write("</td>\r\n");
      out.write("                    <td>");
      out.print((doc.get("mem_headpic") != null && !doc.get("mem_headpic").equals("")) ? "<img src=\"" + doc.get("mem_headpic") + "\" width=\"30\">" : "" );
      out.write("\r\n");
      out.write("                    </td>\r\n");
      out.write("                    <td>");
      out.print(doc.get("province") + "-" + doc.get("city") + "-" + doc.get("area"));
      out.write("\r\n");
      out.write("                    </td>\r\n");
      out.write("                    <td>");

                        if (doc.getIn("mem_addtime") > 0) {
                            out.print(AjaxXml.timeStamp2Date(doc.getIn("mem_addtime"), "YY04-MM-DD HH:MI:SS"));
                        }
                    
      out.write("</td>\r\n");
      out.write("                    ");
      out.write("\r\n");
      out.write("                    <td><a href=\"javascript:addyonghu(");
      out.print(doc.get("id"));
      out.write(",'编辑用户')\">编辑</a> <a\r\n");
      out.write("                            href=\"javascript:del(");
      out.print(doc.get("id") );
      out.write(")\">删除</a></td>\r\n");
      out.write("                </tr>\r\n");
      out.write("\r\n");
      out.write("                ");

                        }
                    }
                
      out.write("\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <td colspan=\"2\" style=\"text-align:center\"><input type=\"checkbox\" name=\"chkall\" id=\"chkall\"\r\n");
      out.write("                                                                     value=\"checkbox\" onclick=\"CheckAll(this.form);\"/>\r\n");
      out.write("                        选中/取消所有\r\n");
      out.write("                    </td>\r\n");
      out.write("                    <td colspan=\"9\" style=\"text-align:right\"><input name=\"tjczft\" type=\"button\" onclick=\"batchdel()\"\r\n");
      out.write("                                                                    value=\"批量删除\"/>");
out.print(AjaxXml.getPage(pages, 10, pn, counts, "", "", "", request));
      out.write("\r\n");
      out.write("                    </td>\r\n");
      out.write("                </tr>\r\n");
      out.write("            </table>\r\n");
      out.write("        </form>\r\n");
      out.write("    </div>\r\n");
      out.write("</div><!--r_iframe END-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div style=\"display:none\"></div>");
      out.write("<!--End Sidebar--></body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
