/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.28
 * Generated at: 2015-12-09 06:12:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.manage.yonghu;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.net.URLDecoder;
import java.util.Iterator;
import java.util.List;
import java.util.ArrayList;
import com.baje.sz.util.*;
import com.baje.sz.ajax.*;
import com.hanyou.admin.sys.*;
import com.baje.sz.util.*;
import com.baje.sz.ajax.*;
import com.hanyou.admin.sys.*;

public final class yonghu_005fedit_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/manage/yonghu/../ini_sys.jsp", Long.valueOf(1448868343606L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("com.hanyou.admin.sys");
    _jspx_imports_packages.add("com.baje.sz.ajax");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("com.baje.sz.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.ArrayList");
    _jspx_imports_classes.add("java.net.URLDecoder");
    _jspx_imports_classes.add("java.util.Iterator");
    _jspx_imports_classes.add("java.util.List");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

    request.setCharacterEncoding("utf-8");
    AdminLogin checklogin = new AdminLogin();
    int userid = 0;
    String user_name = "guest";
    String current_flags = "";
    int gym_group_id = 0, gym_id = 0;
    Selectic utildb = new Selectic();
    Doc currentUser = null;
    int ii = checklogin.checkLogin(request, response);
    if (ii == 0) {
        user_name = checklogin.getuser_name();
        userid = checklogin.getuserid();

        currentUser = utildb.Get_Doc("user_flag,gym_group_id,gym_id", "hy_sys_user", "where id=" + userid, "mysqlss");
        //System.out.println("currentUser="+currentUser);
        if (currentUser != null) {
            current_flags = AjaxXml.getString(currentUser.get("user_flag"));
            //System.out.println("current_flags="+current_flags);
            gym_group_id = currentUser.getIn("gym_group_id");
            gym_id = currentUser.getIn("gym_id");

        }
        //flag=admin_username.get("flag");
    } else {
        out.print("<script>");
        out.print("alert('请登录后再操作');");
        out.print("window.parent.location = '/manage/login.jsp'");
        out.print("</script>");
        return;
    }

      out.write('\r');
      out.write('\n');

    response.setHeader("Pragma", "No-cache");
    response.setHeader("Cache-Control", "no-cache");
    response.setDateHeader("Expires", 0);
    if (!(current_flags.indexOf(",1001,") > -1)) {
        out.print("<script>alert('没有对应的权限');</script>");
        return;
    }
    RequestUtil ru = new RequestUtil(request);
    String action = ru.getString("action");
    int id = ru.getInt("id");
    if (action.equals("save")) {//更新
        UserMember um = new UserMember();
        out.print(um.addOrEditmember(request, userid, user_name, gym_group_id, gym_id));
        return;
    }
    String mem_name = "", mem_username = "", mem_mobile = "", mem_weixin = "", mem_email = "", mem_headpic = "";
    int mem_sex = 0, mem_birth = 0, men_shengao = 0, men_tizhong = 0, men_bufu = 0, mem_province = 0, mem_city = 0, mem_area = 0;

    if (id > 0) {
        Doc doc = utildb.Get_Doc("mem_name,mem_username,mem_mobile,mem_email,mem_weixin," +
                "mem_headpic,mem_sex,mem_birth,men_shengao,men_tizhong,men_bufu,mem_province,mem_city,mem_area", "hy_member", " where id=? and isdel=0", "mysqlss", new Object[]{id});
        if (doc == null) {
            out.print("信息不存在");
            return;
        } else {
            mem_name = URLDecoder.decode(doc.get("mem_name"), "utf-8");
            mem_username = doc.get("mem_username");
            mem_mobile = doc.get("mem_mobile");
            mem_weixin = doc.get("mem_weixin");
            mem_email = doc.get("mem_email");
            mem_headpic = doc.get("mem_headpic");
            mem_sex = doc.getIn("mem_sex");
            mem_birth = doc.getIn("mem_birth");
            men_shengao = doc.getIn("men_shengao");
            men_tizhong = doc.getIn("men_tizhong");
            men_bufu = doc.getIn("men_bufu");
            mem_province = doc.getIn("mem_province");
            mem_city = doc.getIn("mem_city");
            mem_area = doc.getIn("mem_area");
        }
    }

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\"/>\r\n");
      out.write("    <title>table</title>\r\n");
      out.write("    <link href=\"../css/reset.css\" rel=\"stylesheet\" type=\"text/css\"/>\r\n");
      out.write("    <link href=\"../css/base.css\" rel=\"stylesheet\" type=\"text/css\"/>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"../js/jquery-1.7.2.min.js\"></script>\r\n");
      out.write("    <script language=\"javascript\" src='../js/sys.js'></script>\r\n");
      out.write("    <script language=\"javascript\" src='../js/webcalendar.js'></script>\r\n");
      out.write("    <script type='text/javascript' src='/public/js/global.js'></script>\r\n");
      out.write("    <script type='text/javascript' src='/public/js/operamasks/operamasks-ui.min.js'></script>\r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("        function usersave() {\r\n");
      out.write("\r\n");
      out.write("            $(\"#tjbutton\").attr(\"disabled\", true);\r\n");
      out.write("            $(\"#tisspan\").html(\"<img src='../images/loading.gif' />提交中，请稍候……\");\r\n");
      out.write("            $.ajax({\r\n");
      out.write("                dataType: \"json\",\r\n");
      out.write("                type: \"post\",\r\n");
      out.write("                url: \"yonghu_edit.jsp\",\r\n");
      out.write("                data: $(\"#form1\").serialize(),\r\n");
      out.write("                success: function (msg) {\r\n");
      out.write("                    if (msg.type) {\r\n");
      out.write("                        window.parent.art.dialog({\r\n");
      out.write("                            id: 'tisID',\r\n");
      out.write("                            content: msg.msg,\r\n");
      out.write("                            lock: true,\r\n");
      out.write("                            icon: \"succeed\",\r\n");
      out.write("                            cancelVal: '确定',\r\n");
      out.write("                            cancel: function () {\r\n");
      out.write("                                window.parent.location.reload();\r\n");
      out.write("                                window.parent.art.dialog({id: \"tisID\"}).close();\r\n");
      out.write("                                window.parent.art.dialog({id: \"user\"}).close();\r\n");
      out.write("                            }\r\n");
      out.write("                        });\r\n");
      out.write("                    } else {\r\n");
      out.write("                        window.parent.art.dialog.alert(msg.msg);\r\n");
      out.write("                        $(\"#tjbutton\").attr(\"disabled\", false);\r\n");
      out.write("                        $(\"#tisspan\").html(\"\");\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                }\r\n");
      out.write("            });\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        function getCitys(object) {\r\n");
      out.write("            var provinceId = $(object).val();\r\n");
      out.write("            if (provinceId == 0) {\r\n");
      out.write("                return false;\r\n");
      out.write("            } else {\r\n");
      out.write("                $.ajax({\r\n");
      out.write("                    dataType: \"json\",\r\n");
      out.write("                    type: \"post\",\r\n");
      out.write("                    url: \"/manage/ajax/sysajax.jsp\",\r\n");
      out.write("                    data: \"action=getCitysOfProvince&provinceId= \" + provinceId + \" \",\r\n");
      out.write("                    success: function (backJson) {\r\n");
      out.write("                        if (backJson.type) {\r\n");
      out.write("                            var citys = backJson.dataJson;\r\n");
      out.write("                            $(\"#city\").empty();\r\n");
      out.write("                            $(\"#city\").append(\"<option value=\\\"0\\\">--所在城市--</option>\");\r\n");
      out.write("                            for (var i = 0; i < citys.length; i++) {\r\n");
      out.write("                                var option = $(\"<option value=\" + citys[i].cityId + \">\" + citys[i].city + \"</option>\");\r\n");
      out.write("                                $(\"#city\").append(option);\r\n");
      out.write("                            }\r\n");
      out.write("                        }\r\n");
      out.write("                    }\r\n");
      out.write("                });\r\n");
      out.write("\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("        function getAreas(object) {\r\n");
      out.write("            var city_id = $(object).val();\r\n");
      out.write("            if (city_id == 0) {\r\n");
      out.write("                return false;\r\n");
      out.write("            } else {\r\n");
      out.write("                $.ajax({\r\n");
      out.write("                    dataType: \"json\",\r\n");
      out.write("                    type: \"post\",\r\n");
      out.write("                    url: \"/manage/ajax/sysajax.jsp\",\r\n");
      out.write("                    data: \"action=getAreasOfCity&city_id= \" + city_id + \" \",\r\n");
      out.write("                    success: function (backJson) {\r\n");
      out.write("                        if (backJson.type) {\r\n");
      out.write("                            var areas = backJson.dataJson;\r\n");
      out.write("                            $(\"#areaId\").empty();\r\n");
      out.write("                            for (var i = 0; i < areas.length; i++) {\r\n");
      out.write("                                var option = $(\"<option value=\" + areas[i].areaId + \">\" + areas[i].area + \"</option>\");\r\n");
      out.write("                                $(\"#areaId\").append(option);\r\n");
      out.write("                            }\r\n");
      out.write("                        }\r\n");
      out.write("                    }\r\n");
      out.write("                });\r\n");
      out.write("\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    </script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body class=\"ifr\">\r\n");
      out.write("<div id=\"dd\" style=\"padding:5px;\">\r\n");
      out.write("    <div class=\"box_input\">\r\n");
      out.write("        <form id=\"form1\" name=\"form1\" method=\"post\" action=\"\">\r\n");
      out.write("            <input name=\"id\" id=\"id\" type=\"hidden\" value=\"");
      out.print(id);
      out.write("\"/>\r\n");
      out.write("            <input name=\"action\" id=\"action\" type=\"hidden\" value=\"save\"/>\r\n");
      out.write("\r\n");
      out.write("            <ul class=\"row3 clearfix\">\r\n");
      out.write("                <li>帐号：<input type=\"text\" name=\"mem_username\" value=\"");
      out.print(mem_username);
      out.write('"');
      out.write(' ');

                    if (id > 0) {
                        out.print("readonly=\"readonly\"");
                    }
                
      out.write("/></li>\r\n");
      out.write("                <li>会员名称:<input type=\"text\" value=\"");
      out.print(mem_name);
      out.write("\" name=\"mem_name\"/></li>\r\n");
      out.write("                <li>手机号码:<input type=\"text\" value=\"");
      out.print(mem_mobile);
      out.write("\" name=\"mem_mobile\"/></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("            <ul class=\"row3 clearfix\">\r\n");
      out.write("                <li>性别:\r\n");
      out.write("                    <select name=\"mem_sex\">\r\n");
      out.write("                        <option value=\"0\" ");

                            if (mem_sex == 0) {
                                out.print("selected=\"selected\"");
                            }
                        
      out.write(">未设置\r\n");
      out.write("                        </option>\r\n");
      out.write("                        <option value=\"1\" ");

                            if (mem_sex == 1) {
                                out.print("selected=\"selected\"");
                            }
                        
      out.write(">男\r\n");
      out.write("                        </option>\r\n");
      out.write("                        <option value=\"2\" ");

                            if (mem_sex == 2) {
                                out.print("selected=\"selected\"");
                            }
                        
      out.write(">女\r\n");
      out.write("                        </option>\r\n");
      out.write("                    </select>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>邮箱：<input type=\"text\" value=\"");
      out.print(mem_email);
      out.write("\" name=\"mem_email\"/></li>\r\n");
      out.write("                ");
      out.write("\r\n");
      out.write("                <li></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("            <ul class=\"row1 clearfix\">\r\n");
      out.write("                <li>头像图：\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"input\"> <span class=\"upload_file\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div>\r\n");
      out.write("                                        <div class=\"up_input\">\r\n");
      out.write("                                            <input name=\"FileUpload\" id=\"smallfileUpload1\" type=\"file\"/>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"tips\">\r\n");
      out.write("                                            图片尺寸建议：600*230px\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"clear\"></div>\r\n");
      out.write("                                        <input type=\"hidden\" name=\"mem_headpic\"\r\n");
      out.write("                                               value=\"");
      out.print(mem_headpic);
      out.write("\"/>\r\n");
      out.write("                                    </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"img\" id=\"smallfileDetail1\" style=\"width: 100px;\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t</span> </span>\r\n");
      out.write("                </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("            <script type=\"text/javascript\">\r\n");
      out.write("                if ($('#smallfileUpload1').size()) {\r\n");
      out.write("                    global_obj.file_upload($('#smallfileUpload1'),\r\n");
      out.write("                            $('#form1 input[name=mem_headpic]'), $('#smallfileDetail1'),\r\n");
      out.write("                            'web_column');\r\n");
      out.write("                    $('#smallfileDetail1').html(\r\n");
      out.write("                            global_obj.img_link($('#form1 input[name=mem_headpic]').val()));\r\n");
      out.write("                    if ($('#form1 input[name=mem_headpic]').val() != '') {\r\n");
      out.write("                        $('#smallfileDetail1').append('<div class=\"del\">删除</div>');\r\n");
      out.write("                    }\r\n");
      out.write("                    $('#smallfileDetail1 div').click(function () {\r\n");
      out.write("                        $('#form1 input[name=mem_headpic]').val('');\r\n");
      out.write("                        $(this).parent().html('');\r\n");
      out.write("                    });\r\n");
      out.write("                }\r\n");
      out.write("            </script>\r\n");
      out.write("            <ul class=\"row3 clearfix\">\r\n");
      out.write("                ");
      out.write("\r\n");
      out.write("                <li>生日:<input name=\"mem_birth\" type=\"text\" id=\"mem_birth\"\r\n");
      out.write("                              value=\"");
if(mem_birth>0){out.print(AjaxXml.timeStamp2Date(mem_birth, "YY04-MM-DD HH:MI:SS"));} 
      out.write("\"\r\n");
      out.write("                              style=\"width:65px;\" onclick=\"SelectDate(this,'yyyy-MM-dd',0,0)\"/></li>\r\n");
      out.write("                ");
      out.write("\r\n");
      out.write("            </ul>\r\n");
      out.write("            <ul class=\"row3 clearfix\">\r\n");
      out.write("                <li>步幅：<input type=\"text\" name=\"men_bufu\" value=\"");
      out.print(men_bufu);
      out.write("\"/> cm</li>\r\n");
      out.write("                <li>身高：<input type=\"text\" name=\"men_shengao\" value=\"");
      out.print(men_shengao);
      out.write("\"/> cm</li>\r\n");
      out.write("                <li>体重:<input type=\"text\" name=\"men_tizhong\" value=\"");
      out.print(men_tizhong);
      out.write("\"/> kg</li>\r\n");
      out.write("            </ul>\r\n");
      out.write("            <ul class=\"row3 clearfix\">\r\n");
      out.write("                <li>\r\n");
      out.write("                    省份:<select name=\"provinceId\" onchange=\"getCitys(this)\">\r\n");
      out.write("                    <option value=\"0\">--所在省份--</option>\r\n");
      out.write("                    ");

                        List<Doc> provinceList = utildb
                                .Get_List("provinceid,province", "g_province",
                                        " where isdel=0 and country_id=41", "mysqlss");
                        if (provinceList != null) {
                            for (Doc doc : provinceList) {
                                if (doc != null) {
                    
      out.write("\r\n");
      out.write("                    <option value=\"");
      out.print(doc.get("provinceid"));
      out.write("\"\r\n");
      out.write("                            ");

                                if (mem_province == doc.getIn("provinceid")) {
                                    out.print("selected=\"selected\"");
                                }
                            
      out.write('>');
      out.print(doc.get("province"));
      out.write("\r\n");
      out.write("                    </option>\r\n");
      out.write("                    ");

                                }
                            }
                        } else {
                            out.print("<option  value=\"0\">--所在省份--</option>");
                        }
                    
      out.write("\r\n");
      out.write("                </select>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>\r\n");
      out.write("                    城市:");

                    List<Doc> cityList = null;
                    if (mem_province != 0) {
                        cityList = utildb.Get_List("cityid,city", "g_city", "where isdel=0 and province_id=" + mem_province, "mysqlss");
                    }
                
      out.write("\r\n");
      out.write("                    <select name=\"cityId\" id=\"city\" onchange=\"getAreas(this)\">\r\n");
      out.write("                        <option value=\"0\">--所在城市--</option>\r\n");
      out.write("                        ");

                            if (cityList != null) {
                                for (Doc doc : cityList) {
                                    if (doc != null) {
                        
      out.write("\r\n");
      out.write("                        <option value=\"");
      out.print(doc.get("cityid"));
      out.write('"');

                            if (mem_city == doc.getIn("cityid")) {
                                out.print("selected=\"selected\"");
                            }
                        
      out.write(' ');
      out.write('>');
      out.print(doc.get("city"));
      out.write("\r\n");
      out.write("                        </option>\r\n");
      out.write("                        ");

                                    }
                                }
                            } else {
                                out.print("<option  value=\"0\">--所在城市--</option>");
                            }
                        
      out.write("\r\n");
      out.write("                    </select>\r\n");
      out.write("\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>区县:\r\n");
      out.write("                    ");

                        List<Doc> areaList = null;
                        if (mem_city != 0) {
                            areaList = utildb.Get_List("areaid,area", "g_area", "where isdel=0 and city_id=" + mem_city, "mysqlss");
                        }
                    
      out.write("\r\n");
      out.write("                    <select name=\"areaId\" id=\"areaId\">\r\n");
      out.write("                        <option value=\"0\">--所在区县--</option>\r\n");
      out.write("                        ");

                            if (areaList != null) {
                                for (Doc doc : areaList) {
                                    if (doc != null) {
                        
      out.write("\r\n");
      out.write("                        <option value=\"");
      out.print(doc.get("areaid"));
      out.write('"');

                            if (mem_area == doc.getIn("areaid")) {
                                out.print("selected=\"selected\"");
                            }
                        
      out.write(' ');
      out.write('>');
      out.print(doc.get("area"));
      out.write("\r\n");
      out.write("                        </option>\r\n");
      out.write("                        ");

                                    }
                                }
                            } else {
                                out.print("<option  value=\"0\">--所在区县--</option>");
                            }
                        
      out.write("\r\n");
      out.write("                    </select>\r\n");
      out.write("\r\n");
      out.write("                </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("            <div class=\"row_btn\">\r\n");
      out.write("                <button type=\"button\" id=\"tjbutton\" onclick=\"usersave()\">确定提交</button>\r\n");
      out.write("                <span id=\"tisspan\"></span>\r\n");
      out.write("            </div>\r\n");
      out.write("        </form>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("<!--End Sidebar--> </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
