/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.28
 * Generated at: 2015-12-16 02:45:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.share3.member_005fshare;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class share_005fclass_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n");
      out.write("<meta http-equiv=\"Content-type\" name=\"viewport\" content=\"initial-scale=1.0, maximum-scale=1.0, user-scalable=no, width=device-width\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, user-scalable=0, minimum-scale=1.0, maximum-scale=1.0\">\r\n");
      out.write("<title>私教课程分享</title>\r\n");
      out.write("<!-- Mobile Devices Support @begin -->\r\n");
      out.write("    <meta content=\"application/xhtml+xml;charset=UTF-8\" http-equiv=\"Content-Type\">\r\n");
      out.write("    <meta content=\"no-cache,must-revalidate\" http-equiv=\"Cache-Control\">\r\n");
      out.write("    <meta content=\"no-cache\" http-equiv=\"pragma\">\r\n");
      out.write("    <meta content=\"0\" http-equiv=\"expires\">\r\n");
      out.write("    <meta content=\"telephone=no, address=no\" name=\"format-detection\">\r\n");
      out.write("    <meta name=\"apple-mobile-web-app-capable\" content=\"yes\" /> <!-- apple devices fullscreen -->\r\n");
      out.write("    <meta name=\"apple-mobile-web-app-status-bar-style\" content=\"black-translucent\" />\r\n");
      out.write("<!-- Mobile Devices Support @end --> \r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\t/* CSS Document */\r\n");
      out.write("\t*{margin:0;padding:0}\r\n");
      out.write("\thtml{overflow-x:auto}\r\n");
      out.write("\tbody{width:100%; min-height:100%; background:#f5f5f5; -webkit-user-select:none;-webkit-user-drag:none;-webkit-text-size-adjust:none; line-height:1.5em;}\r\n");
      out.write("\tbody, input, textarea, select { font-size: 14px; color: #333; font-family: \"microsoft yahei\", Arial, Helvetica, sans-serif; }\r\n");
      out.write("\timg{ width:100%; border:none;}\r\n");
      out.write("\tbutton{ border:0;background:transparent;font-family:'microsoft yahei','Helvetica Neue',Helvetica,Arial,sans-serif;font-size:16px}\r\n");
      out.write("\tinput,button{-webkit-tap-highlight-color:rgba(255,255,255,0)}\r\n");
      out.write("\tli,ul{list-style:none;}\r\n");
      out.write("\ta { color: #9f3192; text-decoration: none; }\r\n");
      out.write("\ta:hover { color: #333; text-decoration: none; }\r\n");
      out.write("\ta img { border: 0;}\r\n");
      out.write("\t.fl { float: left !important; }\r\n");
      out.write("\t.fr { float: right !important; }\r\n");
      out.write("\t.clear{ clear:both;}\r\n");
      out.write("\t.f_weight{ font-weight:bold;}\r\n");
      out.write("\t.text_c{ text-align:center;}\r\n");
      out.write("\t.text_r{ text-align:right;}\r\n");
      out.write("\t.text_l{ text-align:left;}\r\n");
      out.write("\t.ysh_webkit { display: -webkit-box; -webkit-box-orient: horizontal; }\r\n");
      out.write("\t.ysh_webkit_flex{ -webkit-box-flex: 1; -webkit-box-align: center;}\r\n");
      out.write("\t.title { background:#d33e37; padding:15px; color:#fff;}\r\n");
      out.write("\t.title_img { width:88px; height:88px; border-radius:88px; -moz-border-radius:88px; -webkit-border-radius:88px; margin:0 auto; border:5px solid #c83b34;}\r\n");
      out.write("\t.title_img img {border-radius:88px; -moz-border-radius:88px; -webkit-border-radius:88px;}\r\n");
      out.write("\t.title_con h3 { font-size:18px; font-weight:bold; margin-top:3px; line-height:2em; text-align:center;}\r\n");
      out.write("\t.title_con p { font-size:14px; line-height:2em; text-align:center;} \r\n");
      out.write("\t.title_con span { margin:0 20px; }\r\n");
      out.write("\t.title_pre { margin:10px auto; text-align:center;}\r\n");
      out.write("\t.title_pre i { margin:0 10px 5px; display:inline-block; padding:5px 10px; height:18px; line-height:18px;border:1px solid #fff; -moz-border-radius:5px;-webkit-border-radius:5px; border-radius:5px; font-style:normal;}\r\n");
      out.write("\t.time { color:#999; text-align:center; padding:10px 15px;}\r\n");
      out.write("\t.content {background:#fff; padding:15px 15px 0;}\r\n");
      out.write("\t.con_t { background:url(images/ic_line_6x26.png) no-repeat left center; height:24px; line-height:24px; padding-left:16px; font-size:16px; margin-bottom:10px;}\r\n");
      out.write("\t.con_c { font-size:14px; color:#999; padding:10px 0px 15px; border-top:1px solid #eee; margin-bottom:15px;}\r\n");
      out.write("\t.con_c p { line-height:2em;}\r\n");
      out.write("\t.con_c li { border-bottom:1px solid #eee; height:40px; line-height:40px; text-align:center;}\r\n");
      out.write("\t.con_c em { position:absolute; right:20px;display:inline-block; font-style:normal;}\r\n");
      out.write("\t.con_c span { position:absolute; left:20px; display:inline-block;}\r\n");
      out.write("\t/*浮动层*/\r\n");
      out.write("\t.h70 { height:70px;}\r\n");
      out.write("\t.footer { position:fixed; z-index:999; bottom:0px; left:0px; width:100%;color:#fff; line-height:18px; *zoom:1;  filter:alpha(Opacity=70);  background: rgba(0, 0, 0, 0.7) !important; -moz-opacity:0.7;-khtml-opacity: 0.7; }\r\n");
      out.write("\t.footer .logo{ max-height:44px; max-width:44px; margin:8px 10px;}\r\n");
      out.write("\t.footer .l_title { margin-left:20px;  margin:12px 0; font-size:12px;}\r\n");
      out.write("\t.footer .l_title h3 { font-weight:bold; font-size:18px; margin-bottom:5px; color:#d33e37;}\r\n");
      out.write("\t.footer .botton_download { width:100px; text-align:center; margin:12px; height:36px; color:#fff;  background:#d33e37; border-radius:5px; line-height:36px; font-size:16px;}\r\n");
      out.write("\t.footer .botton_download:hover { background:#c33932; border-radius:5px; cursor:pointer;}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"title\">\r\n");
      out.write("\t<p>教练信息</p>\r\n");
      out.write("\t<div class=\"title_img\"><img src=\"images/user.png\"></div>\r\n");
      out.write("    <div class=\"title_con\">\r\n");
      out.write("      <h3>阿谷</h3>\r\n");
      out.write("      <p>男<span>|</span>28岁</p>\r\n");
      out.write("      <div class=\"title_pre\"><i>增肌</i><i>减肥</i><i>塑形</i></div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"time\">2015-10-27  15:00-16:00</div>\r\n");
      out.write("<div class=\"content\">\r\n");
      out.write("\t<div class=\"con_t\">课程总结</div>\r\n");
      out.write("    <div class=\"con_c\">接下来的训练，要加强小腿和手臂的力量</div>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"content\">\r\n");
      out.write("    <div class=\"con_t\">饮食建议</div>\r\n");
      out.write("    <div class=\"con_c\">\r\n");
      out.write("    <p>1.食物多样，谷类为主，粗细搭配</p>\r\n");
      out.write("    <p>2.多吃蔬菜水果和薯类</p>\r\n");
      out.write("    <p>3. 每天吃奶类、大豆或其制品</p>\r\n");
      out.write("    <p>4. 常吃适量的鱼、禽、蛋和瘦肉</p>\r\n");
      out.write("    <p>5. 减少烹调油用量，吃清淡少盐膳食</p>\r\n");
      out.write("    <p>6. 食不过量，天天运动，保持健康体重</p>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"content\">\r\n");
      out.write("    <div class=\"con_t\">课程列表</div>\r\n");
      out.write("    <div class=\"con_c\">\r\n");
      out.write("    \t<ul>\r\n");
      out.write("        <li><span>杠铃推胸</span>5组<em>15次</em></li>\r\n");
      out.write("        <li><span>哑铃举弯</span>5组<em>14次</em></li>\r\n");
      out.write("        <li><span>绳索推胸</span>5组<em>11次</em></li>\r\n");
      out.write("        <li><span>哑铃侧平举</span>5组<em>9次</em></li>\r\n");
      out.write("        <li><span>单腿伸缩</span>5组<em>12次</em></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"h70\"></div>\r\n");
      out.write("<div class=\"footer ysh_webkit\"> \r\n");
      out.write("        <div class=\"logo\"><img src=\"images/logo.png\"> </div>\t\r\n");
      out.write("        <div class=\"l_title ysh_webkit_flex\">\r\n");
      out.write("            <h3>超能健身</h3>\r\n");
      out.write("            <p>您的智能健身顾问</p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"botton_download\" onclick=\"window.open('#','_self');\">立即下载</div>\t \r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
