/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.28
 * Generated at: 2016-01-20 10:38:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.manage.order;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.hanyou.util.BasicType;
import com.baje.sz.util.Doc;
import com.baje.sz.util.RequestUtil;
import com.hanyou.admin.sys.FitnessPlanTiem;
import net.sf.json.JSONArray;
import net.sf.json.JSONObject;
import java.util.List;
import java.util.ArrayList;
import com.baje.sz.util.*;
import com.baje.sz.ajax.*;
import com.hanyou.admin.sys.*;

public final class default_005faction_005fedit_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/manage/order/../ini_sys.jsp", Long.valueOf(1448868343606L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("com.hanyou.admin.sys");
    _jspx_imports_packages.add("com.baje.sz.ajax");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("com.baje.sz.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.ArrayList");
    _jspx_imports_classes.add("com.hanyou.admin.sys.FitnessPlanTiem");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.hanyou.util.BasicType");
    _jspx_imports_classes.add("com.baje.sz.util.Doc");
    _jspx_imports_classes.add("com.baje.sz.util.RequestUtil");
    _jspx_imports_classes.add("net.sf.json.JSONArray");
    _jspx_imports_classes.add("net.sf.json.JSONObject");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

    request.setCharacterEncoding("utf-8");
    AdminLogin checklogin = new AdminLogin();
    int userid = 0;
    String user_name = "guest";
    String current_flags = "";
    int gym_group_id = 0, gym_id = 0;
    Selectic utildb = new Selectic();
    Doc currentUser = null;
    int ii = checklogin.checkLogin(request, response);
    if (ii == 0) {
        user_name = checklogin.getuser_name();
        userid = checklogin.getuserid();

        currentUser = utildb.Get_Doc("user_flag,gym_group_id,gym_id", "hy_sys_user", "where id=" + userid, "mysqlss");
        //System.out.println("currentUser="+currentUser);
        if (currentUser != null) {
            current_flags = AjaxXml.getString(currentUser.get("user_flag"));
            //System.out.println("current_flags="+current_flags);
            gym_group_id = currentUser.getIn("gym_group_id");
            gym_id = currentUser.getIn("gym_id");

        }
        //flag=admin_username.get("flag");
    } else {
        out.print("<script>");
        out.print("alert('请登录后再操作');");
        out.print("window.parent.location = '/manage/login.jsp'");
        out.print("</script>");
        return;
    }

      out.write('\r');
      out.write('\n');

    response.setHeader("Pragma", "No-cache");
    response.setHeader("Cache-Control", "no-cache");
    response.setDateHeader("Expires", 0);
    if (!current_flags.contains(",2027,")) {
        out.print("<script>alert('没有对应的权限');</script>");
        return;
    }
    RequestUtil ru = new RequestUtil(request);
    String action = ru.getString("action");
    int id = ru.getInt("id");
    if (action.equals("save")) {//更新
        FitnessPlanTiem fp = new FitnessPlanTiem();
        JSONObject json = fp.addaction(request, userid, user_name, gym_group_id, gym_id);
        out.print(json);
        return;
    }
    String title = "", content = "", video_path = "",little_url="", action_time = "", action_device = "", train_position = "",unit_name="";
    int  kal = 0, action_type = 0,coach_id=0,default_value=0,is_hardware=0,unit_type=0;

    if (id > 0) {
        Doc doc = utildb.Get_Doc("title,content,video_path,little_url,coach_id,kal,train_position,action_device,unit_name,unit_type,default_value,is_hardware,action_type ",
                "hy_member_plan_action", " where id=? and isdel=0", "mysqlss", new Object[]{id});
        if (doc == null) {
            out.print("信息不存在");
            return;
        } else {
            title = doc.get("title");
            content = doc.get("content");
            video_path = doc.get("video_path");
            action_time = doc.get("action_time");
            kal = doc.getIn("kal");
            train_position = doc.get("train_position");
            action_device = doc.get("action_device");
            unit_name = doc.get("unit_name");
            action_type = doc.getIn("action_type");
            little_url=doc.get("little_url");
            coach_id=doc.getIn("coach_id");
            unit_type=doc.getIn("unit_type");
            is_hardware=doc.getIn("is_hardware");
            default_value=doc.getIn("default_value");
        }
    }

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\"/>\r\n");
      out.write("    <title>table</title>\r\n");
      out.write("    <link href=\"../css/reset.css\" rel=\"stylesheet\" type=\"text/css\"/>\r\n");
      out.write("    <link href=\"../css/base.css\" rel=\"stylesheet\" type=\"text/css\"/>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"../js/jquery-1.7.2.min.js\"></script>\r\n");
      out.write("    <script language=\"javascript\" src='../js/sys.js'></script>\r\n");
      out.write("    <script language=\"javascript\" src='../js/webcalendar.js'></script>\r\n");
      out.write("    <script type='text/javascript' src='/public/js/global.js'></script>\r\n");
      out.write("    <link href='/public/js/operamasks/operamasks-ui.css' rel='stylesheet' type='text/css'/>\r\n");
      out.write("    <script type='text/javascript' src='/public/js/operamasks/operamasks-ui.min.js'></script>\r\n");
      out.write("    <!-- 七牛上传相关开始 -->\r\n");
      out.write("    <script type=\"text/javascript\" src=\"/js/qiniu_js/demo/js/jquery-1.9.1.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"/js/qiniu_js/demo/bootstrap/js/bootstrap.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"/js/qiniu_js/demo/js/plupload/plupload.full.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"/js/qiniu_js/demo/js/plupload/i18n/zh_CN.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"/js/qiniu_js/demo/js/ui.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"/js/qiniu_js/src/qiniu.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"/js/qiniu_js/demo/js/highlight/highlight.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"/js/qiniu_js/demo/js/main.js\"></script>\r\n");
      out.write("    <!-- 结束 -->\r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("        function actionsave() {\r\n");
      out.write("\r\n");
      out.write("            $(\"#tjbutton\").attr(\"disabled\", true);\r\n");
      out.write("            $(\"#tisspan\").html(\"<img src='../images/loading.gif' />提交中，请稍候……\");\r\n");
      out.write("            $.ajax({\r\n");
      out.write("                dataType: \"json\",\r\n");
      out.write("                type: \"post\",\r\n");
      out.write("                url: \"default_action_edit.jsp\",\r\n");
      out.write("                data: $(\"#form1\").serialize(),\r\n");
      out.write("                success: function (msg) {\r\n");
      out.write("                    if (msg.type) {\r\n");
      out.write("                        window.parent.art.dialog({\r\n");
      out.write("                            id: 'tisID',\r\n");
      out.write("                            content: msg.msg,\r\n");
      out.write("                            lock: true,\r\n");
      out.write("                            icon: \"succeed\",\r\n");
      out.write("                            cancelVal: '确定',\r\n");
      out.write("                            cancel: function () {\r\n");
      out.write("                                window.parent.location.reload();\r\n");
      out.write("                                window.parent.art.dialog({id: \"tisID\"}).close();\r\n");
      out.write("                                window.parent.art.dialog({id: \"user\"}).close();\r\n");
      out.write("                            }\r\n");
      out.write("                        });\r\n");
      out.write("                    } else {\r\n");
      out.write("                        window.parent.art.dialog.alert(msg.msg);\r\n");
      out.write("                        $(\"#tjbutton\").attr(\"disabled\", false);\r\n");
      out.write("                        $(\"#tisspan\").html(\"\");\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                }\r\n");
      out.write("            });\r\n");
      out.write("        }\r\n");
      out.write("        function getUnits(object) {\r\n");
      out.write("            var unit_type = $(object).val();\r\n");
      out.write("            if (unit_type == 0) {\r\n");
      out.write("                return;\r\n");
      out.write("            } else {\r\n");
      out.write("                $.ajax({\r\n");
      out.write("                    dataType: \"json\",\r\n");
      out.write("                    type: \"post\",\r\n");
      out.write("                    url: \"/manage/ajax/sysajax.jsp\",\r\n");
      out.write("                    data: \"action=getGymsOfUnitType&unit_type= \" + unit_type,\r\n");
      out.write("                    success: function (backJson) {\r\n");
      out.write("                        if (backJson.type) {\r\n");
      out.write("                            var unit_values = backJson.dataJson;\r\n");
      out.write("                            $(\"#unit_value\").empty();\r\n");
      out.write("                            $(\"#unit_value\").append(\"<option value=\\\"0\\\">--请选择单位值--</option>\");\r\n");
      out.write("                            for (var i = 0; i < unit_values.length; i++) {\r\n");
      out.write("                                var option = $(\"<option value=\" + unit_values[i].unit_value + \">\" + unit_values[i].unit_value + \"</option>\");\r\n");
      out.write("                                $(\"#unit_value\").append(option);\r\n");
      out.write("                            }\r\n");
      out.write("                        }\r\n");
      out.write("                    }\r\n");
      out.write("                });\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("    </script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body class=\"ifr\">\r\n");
      out.write("<div id=\"dd\" style=\"padding:5px;\">\r\n");
      out.write("    <div class=\"box_input\">\r\n");
      out.write("        <form id=\"form1\" name=\"form1\" method=\"post\" action=\"\">\r\n");
      out.write("            <input name=\"id\" id=\"id\" type=\"hidden\" value=\"");
      out.print(id);
      out.write("\"/>\r\n");
      out.write("            <input name=\"action\" id=\"action\" type=\"hidden\" value=\"save\"/>\r\n");
      out.write("            <ul class=\"row3 clearfix\">\r\n");
      out.write("            <li>\r\n");
      out.write("            \t教练名：<select name=\"coach_id\">\r\n");
      out.write("            \t\t<option value=\"0\">系统默认动作</option>\r\n");
      out.write("            \t\t");

                			List<Doc> coachList=utildb.Get_List("id,coach_name", "hy_coach","where isdel=0","mysqlss");
                			if(coachList!=null){
                				for(Doc doc:coachList){
                					
      out.write("\r\n");
      out.write("                \t\t\t\t\t\t<option value=\"");
      out.print(doc.getIn("id"));
      out.write('"');
      out.print(doc.getIn("id")==coach_id?"selected=\"coach_id\"":"");
      out.write('>');
      out.print(doc.get("coach_name"));
      out.write("</option>\r\n");
      out.write("                \t\t\t\t\t");

                				}
                			}
                		
      out.write("\r\n");
      out.write("            \t</select>\r\n");
      out.write("            </li>\r\n");
      out.write("                <li>动作类型：\r\n");
      out.write("                    <select name=\"action_type\" id=\"action_type\" style=\"width:100px;\">\r\n");
      out.write("                        <option value=\"0\">--请选择动作类型--</option>\r\n");
      out.write("                        ");

                            JSONArray actionTypes = utildb.getJsonArray("select type_name,id from hy_member_action_type where isdel=0 and type=0 ", "", new ArrayList());
                            if (!actionTypes.isEmpty()) {
                                for (Object o : actionTypes) {
                                    JSONObject actionObj = JSONObject.fromObject(o);
                                    if (actionObj.optInt("id") == action_type) {
                                        out.print("<option value=" + actionObj.optInt("id") + " selected>" + actionObj.optString("type_name") + "</option>");
                                    } else {
                                        out.print("<option value=" + actionObj.optInt("id") + ">" + actionObj.optString("type_name") + "</option>");
                                    }
                                }
                            }
                        
      out.write("\r\n");
      out.write("                    </select>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>动作名称：<input type=\"text\" name=\"title\" value=\"");
      out.print(title);
      out.write("\" style=\"width:100px;\"/></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("            <ul class=\"row3 clearfix\">\r\n");
      out.write("             <li>训练部位：<input type=\"text\" value=\"");
      out.print(train_position );
      out.write("\" name=\"train_position\" style=\"width:100px;\"/>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>训练机械：<input type=\"text\" value=\"");
      out.print(action_device );
      out.write("\" name=\"action_device\" style=\"width:100px;\"/></li>\r\n");
      out.write("                 <li>卡路里：<input type=\"text\" value=\"");
      out.print(kal>0?kal:"");
      out.write("\" name=\"kal\" size=\"5\"/>(kal)</li>\r\n");
      out.write("            </ul>\r\n");
      out.write("            <ul class=\"row3 clearfix\">\r\n");
      out.write("             <li>是否支持智能设备：<input type=\"radio\" value=\"1\" name=\"is_hardware\" ");
      out.print(is_hardware==1?"checked=\"checked\"":"");
      out.write("/>是 <input type=\"radio\" value=\"0\" name=\"is_hardware\" ");
      out.print(is_hardware==0?"checked=\"checked\"":"");
      out.write("/> 否\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>单位值:<select name=\"unit_type\">\r\n");
      out.write("                \t");

                		List<Doc> list=BasicType.getUnitTypeList();
                		if(list!=null){
                			for(Doc doc:list){
                				
      out.write("\r\n");
      out.write("                \t\t\t\t<option value=\"");
      out.print(doc.getIn("id"));
      out.write('"');
      out.write(' ');
      out.print(unit_type==doc.getIn("id")?"selected=\"selected\":":"");
      out.write('>');
      out.print(doc.get("name"));
      out.write("</option>\r\n");
      out.write("                \t\t\t\t");

                			}
                		}
                	
      out.write("\r\n");
      out.write("                </select>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li>默认值：\r\n");
      out.write("                \t<input type=\"text\" name=\"default_value\" value=\"");
      out.print(default_value>0?default_value:"");
      out.write("\"/> ");
      out.print(BasicType.getUnitTypeName(unit_type));
      out.write("\r\n");
      out.write("                </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("            <ul class=\"row1 clearfix\">\r\n");
      out.write("                <li>\r\n");
      out.write("                        <label>\r\n");
      out.write("                            视频路径：\r\n");
      out.write("                        </label>\r\n");
      out.write("                        <div class=\"container\">\r\n");
      out.write("\t\t\t\t\t\t\t    <div class=\"body\">\r\n");
      out.write("       <div>\r\n");
      out.write("        <div class=\"col-md-12\">\r\n");
      out.write("            <div id=\"container\">\r\n");
      out.write("               <input type=\"button\" value=\"选择文件\" id=\"pickfiles\" style=\"width:80px;height:30px;background-color: #9AFF9A;border-style: ridge;\"/>\r\n");
      out.write("            \t");

            		if(video_path!=null&&!"".equals(video_path)){
            			out.print("<input type=\"hidden\" name=\"video_path\" value=\""+video_path+"\"/><span id=\"show_path\">"+video_path+"</span>");
            		}
            	
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write(" <div id=\"fsUploadProgress\" style=\"width:opx;background-color:#9AFF9A;text-align: center;margin-top:3px;\"></div>\r\n");
      out.write("                </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("            <ul>\r\n");
      out.write("                <li>动作介绍:<textarea rows=\"5\" cols=\"100\" name=\"content\">");
      out.print(content);
      out.write("</textarea></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("            <div class=\"row_btn\">\r\n");
      out.write("                <button type=\"button\" id=\"tjbutton\" onclick=\"actionsave()\">确定提交</button>\r\n");
      out.write("                <span id=\"tisspan\"></span>\r\n");
      out.write("            </div>\r\n");
      out.write("        </form>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<!--End Sidebar-->\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
