/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.28
 * Generated at: 2015-12-25 07:50:15 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.manage.order;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.math.BigDecimal;
import java.text.DecimalFormat;
import java.net.URLDecoder;
import java.net.URLEncoder;
import com.hanyou.util.BasicType;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import com.baje.sz.ajax.*;
import com.baje.sz.util.*;
import com.hanyou.admin.sys.*;
import com.baje.sz.util.*;
import com.baje.sz.ajax.*;
import com.hanyou.admin.sys.*;

public final class user_005fmoney_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/manage/order/../end.jsp", Long.valueOf(1448868342872L));
    _jspx_dependants.put("/manage/order/../left.jsp", Long.valueOf(1451029560124L));
    _jspx_dependants.put("/manage/order/../ini_sys.jsp", Long.valueOf(1448868343606L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("com.hanyou.admin.sys");
    _jspx_imports_packages.add("com.baje.sz.ajax");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("com.baje.sz.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.ArrayList");
    _jspx_imports_classes.add("java.net.URLEncoder");
    _jspx_imports_classes.add("java.net.URLDecoder");
    _jspx_imports_classes.add("java.util.Iterator");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.hanyou.util.BasicType");
    _jspx_imports_classes.add("java.math.BigDecimal");
    _jspx_imports_classes.add("java.text.DecimalFormat");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

    request.setCharacterEncoding("utf-8");
    AdminLogin checklogin = new AdminLogin();
    int userid = 0;
    String user_name = "guest";
    String current_flags = "";
    int gym_group_id = 0, gym_id = 0;
    Selectic utildb = new Selectic();
    Doc currentUser = null;
    int ii = checklogin.checkLogin(request, response);
    if (ii == 0) {
        user_name = checklogin.getuser_name();
        userid = checklogin.getuserid();

        currentUser = utildb.Get_Doc("user_flag,gym_group_id,gym_id", "hy_sys_user", "where id=" + userid, "mysqlss");
        //System.out.println("currentUser="+currentUser);
        if (currentUser != null) {
            current_flags = AjaxXml.getString(currentUser.get("user_flag"));
            //System.out.println("current_flags="+current_flags);
            gym_group_id = currentUser.getIn("gym_group_id");
            gym_id = currentUser.getIn("gym_id");

        }
        //flag=admin_username.get("flag");
    } else {
        out.print("<script>");
        out.print("alert('请登录后再操作');");
        out.print("window.parent.location = '/manage/login.jsp'");
        out.print("</script>");
        return;
    }

      out.write('\r');
      out.write('\n');

    response.setHeader("Pragma", "No-cache");
    response.setHeader("Cache-Control", "no-cache");
    response.setDateHeader("Expires", 0);
    request.setCharacterEncoding("utf-8");
    if (current_flags.indexOf(",2033,") < 0) {
        response.sendRedirect("../error.jsp?left=jianshenfang");
        return;
    }

    RequestUtil ru = new RequestUtil(request);
    String action = ru.getString("action");
    if (action.equals("del")) {
        DeviceAPI deviceApi = new DeviceAPI();
        out.print(deviceApi.delDeviceType(request, userid, user_name,
                gym_group_id, gym_id).toString());
        return;
    }
    if (action.equals("batchDel")) {
        DeviceAPI deviceApi = new DeviceAPI();
        out.print(deviceApi.batchDelDeviceType(request, userid,
                user_name, gym_group_id, gym_id).toString());
        return;

    }
    int pages = ru.getInt("page");
    if (pages == 0) {
        pages = 1;
    }
    int pn = ru.getInt("pn");
    if (pn == 0) {
        pn = 20;
    }
    String mem_name = ru.getString("mem_name");
    int gymGroupId = ru.getInt("gymGroupId");
    int gymId = ru.getInt("gymId");
    int record_type=ru.getInt("record_type");
    int in_or_de=ru.getInt("in_or_de");

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\"/>\r\n");
      out.write("    <title>table</title>\r\n");
      out.write("    <link href=\"../css/reset.css\" rel=\"stylesheet\" type=\"text/css\"/>\r\n");
      out.write("    <link href=\"../css/base.css\" rel=\"stylesheet\" type=\"text/css\"/>\r\n");
      out.write("    <link href=\"../css/page.css\" rel=\"stylesheet\" type=\"text/css\"/>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"../js/jquery-1.7.2.min.js\">\r\n");
      out.write("    </script>\r\n");
      out.write("    <script type=\"text/javascript\"\r\n");
      out.write("            src=\"../js/artDialog4.1.6/artDialog.js?skin=green\">\r\n");
      out.write("    </script>\r\n");
      out.write("    <script type=\"text/javascript\"\r\n");
      out.write("            src=\"../js/artDialog4.1.6/plugins/iframeTools.source.js\">\r\n");
      out.write("    </script>\r\n");
      out.write("    <script language=\"javascript\" src='../js/sys.js'>\r\n");
      out.write("    </script>\r\n");
      out.write("    <script language=\"javascript\" src='/manage/js/webcalendar.js'>\r\n");
      out.write("    </script>\r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("        function getGyms(object) {\r\n");
      out.write("            var gymGroupId = $(object).val();\r\n");
      out.write("            if (gymGroupId == 0) {\r\n");
      out.write("                return false;\r\n");
      out.write("            } else {\r\n");
      out.write("                $.ajax({\r\n");
      out.write("                    dataType: \"json\",\r\n");
      out.write("                    type: \"post\",\r\n");
      out.write("                    url: \"/manage/ajax/sysajax.jsp\",\r\n");
      out.write("                    data: \"action=getGymsOfGymGroup&gymGroupId= \" + gymGroupId + \" \",\r\n");
      out.write("                    success: function (backJson) {\r\n");
      out.write("                        if (backJson.type) {\r\n");
      out.write("                            var gyms = backJson.dataJson;\r\n");
      out.write("                            $(\"#gymId\").empty();\r\n");
      out.write("                            $(\"#gymId\").append(\r\n");
      out.write("                                    \"<option value=\\\"0\\\">--请选择健身房--</option>\");\r\n");
      out.write("                            for (var i = 0; i < gyms.length; i++) {\r\n");
      out.write("                                var option = $(\"<option value=\" + gyms[i].id + \">\"\r\n");
      out.write("                                        + gyms[i].gym_name + \"</option>\");\r\n");
      out.write("                                $(\"#gymId\").append(option);\r\n");
      out.write("                            }\r\n");
      out.write("                        }\r\n");
      out.write("                    }\r\n");
      out.write("                });\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("    </script>\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"ifr\">\r\n");
      out.write("\r\n");
      out.write("<link href=\"/manage/css/colortemplate.css\" rel=\"stylesheet\" type=\"text/css\"/>\r\n");
      out.write("<div class=\"sidebarWrap\">\r\n");
      out.write("\t");

		if(gym_group_id==0){
	
      out.write("\r\n");
      out.write("\t    <div class=\"sidebar\" id=\"yonghu\" style=\"display:none\">\r\n");
      out.write("        <h3>\r\n");
      out.write("            <span>用户管理</span>\r\n");
      out.write("        </h3>\r\n");
      out.write("        <ul class=\"nav_list\">\r\n");
      out.write("\r\n");
      out.write("            ");

                if (current_flags.contains("1001")) {
            
      out.write("\r\n");
      out.write("            <li><a href=\"javascript:window.parent.jianyi2('yonghu/yonghu.jsp','用户管理')\">用户管理</a></li>\r\n");
      out.write("            ");

                }
                if (current_flags.contains("1004")) {
            
      out.write("\r\n");
      out.write("             <li><a href=\"javascript:window.parent.jianyi2('yonghu/level_experience_group.jsp?group_type=1','积分操作组别')\">积分操作组别</a></li>\r\n");
      out.write("            ");

                }
                if (current_flags.contains("1005")) {
            
      out.write("\r\n");
      out.write("           <li><a href=\"javascript:window.parent.jianyi2('yonghu/level_experience_operating.jsp?operating_type=1','积分操作')\">积分操作</a></li>\r\n");
      out.write("            ");

                }
                if (current_flags.contains("1007")) {
            
      out.write("\r\n");
      out.write("             <li><a href=\"javascript:window.parent.jianyi2('yonghu/level_experience_operating_user.jsp?operating_type=1','积分获取情况')\">积分获取情况</a></li>\r\n");
      out.write("            ");

                }
               
      out.write("\r\n");
      out.write("        </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("\t");

		}
	
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div class=\"sidebar\" id=\"jianshenfang\" style=\"display:none\">\r\n");
      out.write("        <h3>\r\n");
      out.write("            <span>健身房管理</span>\r\n");
      out.write("        </h3>\r\n");
      out.write("        <ul class=\"nav_list\">\r\n");
      out.write("            ");

                if (gym_group_id == 0) {
                    if (current_flags.contains("3001")) {
            
      out.write("\r\n");
      out.write("            <li><a href=\"javascript:window.parent.jianyi2('jianshenfang/jituan.jsp','连锁集团管理')\">连锁集团管理</a></li>\r\n");
      out.write("            ");

                    }
                }
						 if(gym_id==0){  
                if (current_flags.contains("3005")) {
            
      out.write("\r\n");
      out.write("            <li><a href=\"javascript:window.parent.jianyi2('jianshenfang/gym.jsp','健身房管理')\">健身房管理</a></li>\r\n");
      out.write("            ");

                }
					  	} 
                if (current_flags.contains("3009")) {
            
      out.write("\r\n");
      out.write("            <li><a href=\"javascript:window.parent.jianyi2('jianshenfang/coach.jsp','教练管理')\">教练管理</a></li>\r\n");
      out.write("            ");
}
				if (current_flags.contains("3045")) { 
				
      out.write("\r\n");
      out.write("            <li><a href=\"javascript:window.parent.jianyi2('jianshenfang/device.jsp','设备管理')\">设备管理</a></li>\r\n");
      out.write("            ");

                 }
                 if (current_flags.contains("3049")) {
             
      out.write("\r\n");
      out.write("             <li>\r\n");
      out.write("                 <a href=\"javascript:window.parent.jianyi2('jianshenfang/bodyMeasure_titai.jsp', '体态管理')\">体态管理</a>\r\n");
      out.write("             </li>\r\n");
      out.write("             ");

                 } 
                 if(current_flags.contains("3050")){
                 	
      out.write("\r\n");
      out.write("                 \t <li>\r\n");
      out.write("                 <a href=\"javascript:window.parent.jianyi2('jianshenfang/bodyMeasure_tineng.jsp', '体能管理')\">体能管理</a>\r\n");
      out.write("             </li>\r\n");
      out.write("                 \t");

                 }
                 if(current_flags.contains("3051")){
              		
      out.write("\r\n");
      out.write("              \t\t  <li><a href=\"javascript:window.parent.jianyi2('jianshenfang/bodyMeasure_tice.jsp', '体测管理')\">体测管理</a>\r\n");
      out.write("            \t\t\t\t </li>\r\n");
      out.write("              \t\t");

                 }
                if (current_flags.contains("3017")) {
            
      out.write("\r\n");
      out.write("            <li>\r\n");
      out.write("                <a href=\"javascript:window.parent.jianyi2('jianshenfang/gym_member_book.jsp?book_type=1','预约私教')\">预约私教</a>\r\n");
      out.write("            </li>\r\n");
      out.write("            ");
 
                }
            
      out.write("\r\n");
      out.write("        </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"sidebar\" id=\"order\" style=\"display:none\">\r\n");
      out.write("        <h3>\r\n");
      out.write("            <span>订单管理</span>\r\n");
      out.write("        </h3>\r\n");
      out.write("        <ul class=\"nav_list\">\r\n");
      out.write("            ");
if (current_flags.contains("2007")) { 
      out.write("\r\n");
      out.write("            <li><a href=\"javascript:window.parent.jianyi2('order/hy_order.jsp','订单管理')\">订单管理</a></li>\r\n");
      out.write("            ");

                }
            if(gym_group_id==0){
                if (current_flags.contains("2026")) {
            
      out.write("\r\n");
      out.write("            <li><a href=\"javascript:window.parent.jianyi2('order/plan_action_type.jsp','动作类型')\">动作类型</a></li>\r\n");
      out.write("            ");

                }
                if (current_flags.contains("2027")) {
            
      out.write("\r\n");
      out.write("            <li><a href=\"javascript:window.parent.jianyi2('order/default_action.jsp','默认动作')\">默认动作</a></li>\r\n");
      out.write("            ");

                }
                if (current_flags.contains("2028")) {
            
      out.write("\r\n");
      out.write("            <li><a href=\"javascript:window.parent.jianyi2('order/plan_action_type.jsp?type=1','健身目标')\">健身目标</a></li>\r\n");
      out.write("             ");
} if (current_flags.contains("2029")) {
                            
      out.write("\r\n");
      out.write("                            <li>\r\n");
      out.write("                                <a href=\"javascript:window.parent.jianyi2('order/common_language_class.jsp?','常用语类型')\">常用语类型</a>\r\n");
      out.write("                            </li>");

                } if(current_flags.contains("2030")){
                	
      out.write("\r\n");
      out.write("                \t <li>\r\n");
      out.write("                    \t<a href=\"javascript:window.parent.jianyi2('order/common_language.jsp','常用语设置')\">常用语设置</a>\r\n");
      out.write("                \t</li>\r\n");
      out.write("                \t");

                	
                } if(current_flags.contains("2031")){
                    	
      out.write("\r\n");
      out.write("                    \t<li><a href=\"javascript:window.parent.jianyi2('order/pro_class.jsp?class_status=1','商品栏目')\">商品栏目</a></li>\r\n");
      out.write("                    \t");

                    }
            }
                if(current_flags.contains("2032")){
                    	
      out.write("\r\n");
      out.write("                    \t <li><a href=\"javascript:window.parent.jianyi2('order/pro_product.jsp','商品管理')\">商品管理</a></li>\r\n");
      out.write("                    \t");

                    }if(current_flags.contains("2033")){
                    	
      out.write("\r\n");
      out.write("                   \t<li><a href=\"javascript:window.parent.jianyi2('order/user_money.jsp','用户资金记录')\">用户资金记录</a></li>\r\n");
      out.write("                   \t");

                   } 
      out.write("\r\n");
      out.write("             </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("    ");

    if(gym_group_id==0){
        if (current_flags.contains("4004")) {
    
      out.write("\r\n");
      out.write("    <div class=\"sidebar\" id=\"xinxi\" style=\"display:none\">\r\n");
      out.write("        <h3>\r\n");
      out.write("            <span>信息管理</span>\r\n");
      out.write("        </h3>\r\n");
      out.write("        <ul class=\"nav_list\">\r\n");
      out.write("            ");
 if (current_flags.contains("4002")) {
      out.write("\r\n");
      out.write("            <li><a href=\"javascript:window.parent.jianyi2('xinxi/news.jsp','信息内容')\">信息内容</a></li>\r\n");
      out.write("            ");

                }
                if (current_flags.contains("4001")) {
            
      out.write("\r\n");
      out.write("            <li><a href=\"javascript:window.parent.jianyi2('xinxi/newsclass.jsp','信息栏目')\">信息栏目</a></li>\r\n");
      out.write("\r\n");
      out.write("            ");

                }
                if (current_flags.contains("4003")) {
            
      out.write("\r\n");
      out.write("            <li><a href=\"javascript:window.parent.jianyi2('xinxi/news_edit.jsp','发布信息')\">发布信息</a></li>\r\n");
      out.write("            ");

                }
            
      out.write("\r\n");
      out.write("        </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("    ");

        }
    }
    
      out.write("\r\n");
      out.write("    ");

    	if(gym_group_id==0){
    
      out.write("\r\n");
      out.write("    <div class=\"sidebar\" id=\"faxian\" style=\"display:none\">\r\n");
      out.write("        <h3>\r\n");
      out.write("            <span>发现管理</span>\r\n");
      out.write("        </h3>\r\n");
      out.write("        <ul class=\"nav_list\">\r\n");
      out.write("            ");
 if (current_flags.contains("5001")) { 
      out.write("\r\n");
      out.write("            <li><a href=\"javascript:window.parent.jianyi2('faxian/wenzhang.jsp','发现文章')\">发现文章</a></li>\r\n");
      out.write("            ");

                }
                if (current_flags.contains("5005")) {
            
      out.write("\r\n");
      out.write("            <li><a href=\"javascript:window.parent.jianyi2('faxian/huifu.jsp','文章评论')\">文章评论</a></li>\r\n");
      out.write("            ");

                }
                if (current_flags.contains("5007")) {
            
      out.write("\r\n");
      out.write("            <li><a href=\"javascript:window.parent.jianyi2('faxian/hy_friendster_carousel.jsp','每日推荐')\">每日推荐</a></li>\r\n");
      out.write("            ");
} 
      out.write("\r\n");
      out.write("        </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("\t");

    	}
	
      out.write("\r\n");
      out.write("    <div class=\"sidebar\" id=\"xitong\" style=\"display:none\">\r\n");
      out.write("        <h3>\r\n");
      out.write("            <span>系统管理管理</span>\r\n");
      out.write("        </h3>\r\n");
      out.write("        <ul class=\"nav_list\">\r\n");
      out.write("            ");

          if(gym_group_id==0){
            if (current_flags.contains("6001")) { 
      out.write("\r\n");
      out.write("            <li><a href=\"javascript:window.parent.jianyi2('xitong/rizhi.jsp','系统日志')\">系统日志</a></li>\r\n");
      out.write("            <li><a href=\"javascript:window.parent.jianyi2('xitong/rizhi.jsp?log_type=2','教练系统日志')\">教练系统日志</a></li>\r\n");
      out.write("            ");

                }
                if (current_flags.contains("6002")) {
            
      out.write("\r\n");
      out.write("            <li><a href=\"javascript:window.parent.jianyi2('xitong/keyword.jsp','关键词管理')\">关键词管理</a></li>\r\n");
      out.write("            ");

                }
                if (current_flags.contains("6009")) {
            
      out.write("\r\n");
      out.write("            <li><a href=\"javascript:window.parent.jianyi2('xitong/thirdPartyApply.jsp','加盟申请')\">加盟申请</a></li>\r\n");
      out.write("            ");

                }
                if (current_flags.contains("6006")) {
            
      out.write("\r\n");
      out.write("            <li><a href=\"javascript:window.parent.jianyi2('xitong/guanliyuan.jsp','后台管理员管理')\">后台管理员管理</a></li>\r\n");
      out.write("            ");

                }
                if (current_flags.contains("6003")) {
            
      out.write("\r\n");
      out.write("            <li><a href=\"javascript:window.parent.jianyi2('xitong/userfeedback.jsp','用户反馈')\">用户反馈</a></li>\r\n");
      out.write("            ");

                }
                if (current_flags.contains("6008")) {
            
      out.write("\r\n");
      out.write("            <li><a href=\"javascript:window.parent.jianyi2('xitong/tuisong.jsp','会员推送')\">会员推送</a></li>\r\n");
      out.write("            ");

            }
          }
            
      out.write("\r\n");
      out.write("            <li><a href=\"javascript:window.parent.jianyi2('xitong/password_edit.jsp','修改密码')\">修改密码</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("    $(document).ready(\r\n");
      out.write("            function () {\r\n");
      out.write("                var leftarr = ['yonghu', 'order', 'jianshenfang', 'xinxi', 'xitong', 'faxian'];\r\n");
      out.write("                var nowhref = window.location.href;\r\n");
      out.write("                for (l in leftarr) {\r\n");
      out.write("                    if (nowhref.indexOf(leftarr[l]) > -1) {\r\n");
      out.write("                        $(\"#\" + leftarr[l]).show();\r\n");
      out.write("                    } else {\r\n");
      out.write("                        $(\"#\" + leftarr[l]).hide();\r\n");
      out.write("                    }\r\n");
      out.write("                }\r\n");
      out.write("            });\r\n");
      out.write("</script>");
      out.write("<!--End Sidebar-->\r\n");
      out.write("<div class=\"iframe_box\">\r\n");
      out.write("    <div class=\"form_info\">\r\n");
      out.write("        <strong>用户资金记录列表</strong>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"form_cont mb10\">\r\n");
      out.write("        <form id=\"form1\" name=\"form1\" method=\"get\" action=\"\">\r\n");
      out.write("        <ul class=\"row3\" style=\"margin-top: 3px;\">\r\n");
      out.write("        \t ");

                    if (gym_group_id == 0) {
                
      out.write("\r\n");
      out.write("                <li>所属连锁：\r\n");
      out.write("                    <select name=\"gymGroupId\" onchange=\"getGyms(this)\">\r\n");
      out.write("                        <option value=\"0\">--请选择连锁--</option>\r\n");
      out.write("                        ");
      out.print(BasicType.getLianSuo(gymGroupId, gym_group_id));
      out.write("\r\n");
      out.write("                    </select>\r\n");
      out.write("                </li>\r\n");
      out.write("                ");

                    }
                
      out.write("\r\n");
      out.write("\r\n");
      out.write("                ");

                    if (gym_id == 0) {
                
      out.write("\r\n");
      out.write("                <li>健身房：\r\n");
      out.write("                    <select name=\"gymId\" id=\"gymId\">\r\n");
      out.write("                        <option value=\"0\">--请选择健身房--</option>\r\n");
      out.write("                        ");
      out.print(BasicType.getJianShenFang(gymId, gym_group_id, gym_id));
      out.write("\r\n");
      out.write("                    </select>\r\n");
      out.write("                </li>\r\n");
      out.write("                ");

                    }
                
      out.write("\r\n");
      out.write("                <li>记录类型：\r\n");
      out.write("                \t<select name=\"record_type\">\r\n");
      out.write("                \t\t<option value=\"0\">--全部--</option>\r\n");
      out.write("                \t\t<option value=\"1\" ");
      out.print(record_type==1?"selected=\"selected\"":"");
      out.write(">--充值--</option>\r\n");
      out.write("                \t\t<option value=\"2\" ");
      out.print(record_type==2?"selected=\"selected\"":"");
      out.write(">--购买商品--</option>\r\n");
      out.write("                \t</select>\r\n");
      out.write("                </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("            <ul class=\"row3\" style=\"margin-top: 3px;\">\r\n");
      out.write("             <li>流向类型：\r\n");
      out.write("                \t<select name=\"in_or_de\">\r\n");
      out.write("                \t\t<option value=\"0\">--全部--</option>\r\n");
      out.write("                \t\t<option value=\"1\" ");
      out.print(in_or_de==1?"selected=\"selected\"":"");
      out.write(">--增加--</option>\r\n");
      out.write("                \t\t<option value=\"2\" ");
      out.print(in_or_de==2?"selected=\"selected\"":"");
      out.write(">--减少--</option>\r\n");
      out.write("                \t</select>\r\n");
      out.write("                </li>\r\n");
      out.write("                 <li>会员名称：<input name=\"mem_name\" type=\"text\" id=\"mem_name\" value=\"");
      out.print(mem_name);
      out.write("\" style=\"width:100px;\"/>\r\n");
      out.write("                </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("            <ul class=\"row3\" style=\"margin-top:3px;\">\r\n");
      out.write("                <li class=\"btn_line\" style=\"margin-top:3px;\">\r\n");
      out.write("                    <button type=\"button\" class=\"btn_formA\" onclick=\"$('#form1').submit()\">查&nbsp;&nbsp;询</button>\r\n");
      out.write("                </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </form>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"form_table\">\r\n");
      out.write("        <form id=\"form2\" name=\"form2\" method=\"post\" action=\"\"\r\n");
      out.write("              autocomplete=\"off\">\r\n");
      out.write("            <table cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <th width=\"3%\">&nbsp;</th>\r\n");
      out.write("                     <th width=\"12%\">所属连锁</th>\r\n");
      out.write("                    <th width=\"12%\">所属健身房</th> \r\n");
      out.write("                    <th width=\"10%\">会员名称</th>\r\n");
      out.write("                    <th width=\"12%\">订单号</th>\r\n");
      out.write("                    <th width=\"12%\">记录类型</th>\r\n");
      out.write("                    <th width=\"12%\">增加/减少</th>\r\n");
      out.write("                    <th width=\"13%\">记录金额</th>\r\n");
      out.write("                    <th width=\"\">添加时间</th>\r\n");
      out.write("                </tr>\r\n");
      out.write("                ");

                    String table = "wechat_user_funds a left join hy_gym_group b on a.gym_group_id=b.id left join hy_gym c on a.gym_id=c.id" +
                            " left join wx_card_user m on a.wechat_userid=m.id ";
                    StringBuffer sb = new StringBuffer(" a.isdel=0 ");
                    List sqllist = new ArrayList();
					if (gym_group_id > 0) {
						sb.append(" and a.gym_group_id=? ");
						sqllist.add(gym_group_id);
					} else {
						if (gymGroupId > 0) {
							sb.append(" and a.gym_group_id=? ");
							sqllist.add(gymGroupId);
						}
					}
					if (gym_id > 0) {
						sb.append(" and a.gym_id=? ");
						sqllist.add(gym_id);
					} else {
						if (gymId > 0) {
							sb.append(" and a.gym_id=? ");
							sqllist.add(gymId);
						}
					} 
					if(record_type>0){
						sb.append(" and a.funds_type=? ");
						sqllist.add(record_type);
					}
					if(in_or_de>0){
						sb.append(" and a.in_or_de=? ");
						sqllist.add(in_or_de);
					}
					 if (!"".equals(mem_name)) {
	                        sb.append(" and m.username like ?");
	                        sqllist.add("%" + mem_name + "%");
	                  }
                    String file = "a.funds_type,a.in_or_de,a.funds_money,a.order_no,a.create_time,b.group_name,c.gym_name,m.username";
                    String order = " order by a.id desc";
                    String idd = "a.id";
                    int counts = utildb.Get_count(idd, table, sb.toString(), "mysqlss", sqllist);
                    List list = utildb.Get_List(pages, pn, counts, table, sb.toString(), file, order, "mysqlss", sqllist);
                    DecimalFormat df = new DecimalFormat("0.00");
                    //资金总数(select in_or_de,sum(funds_money) as 'counts' from wechat_user_funds  group by in_or_de where isdel=0)
                    List money_list=new ArrayList();
                    StringBuffer money_sb=new StringBuffer(" where a.isdel=0 ");
                    if (!"".equals(mem_name)) {
                    	money_sb.append(" and b.username like ?");
                    	money_list.add("%" + mem_name + "%");
                    }
                    List<Doc> countList=utildb.Get_List("a.in_or_de,sum(a.funds_money) as 'moneys' ", "wechat_user_funds a left join wx_card_user b on a.wechat_userid=b.id ",money_sb.toString()+" group by a.in_or_de ","mysqlss",money_list);
                   	BigDecimal bd_in=new BigDecimal("0");
                   	BigDecimal bd_de=new BigDecimal("0");
                   	if(countList!=null){
                   		for(Doc doc:countList){
                   			if(doc.getIn("in_or_de")==1){
                   				bd_in=bd_in.add(new BigDecimal(doc.get("moneys","0")));
                   			}else if(doc.getIn("in_or_de")==-1){
                   				bd_de=bd_de.add(new BigDecimal(doc.get("moneys","0")));
                   			}
                   		}
                   	}
                    if (list != null) {
                        for (Iterator its = list.listIterator(); its.hasNext(); ) {
                            Doc doc = (Doc) its.next();
                
      out.write("\r\n");
      out.write("                <tr onmousemove=\"tableMove(this);\" onmouseout=\"tableOut(this)\">\r\n");
      out.write("                    <td>\r\n");
      out.write("                        <input name=\"id\" type=\"checkbox\" id=\"id\" value=\"");
      out.print(doc.get("id"));
      out.write("\"/>\r\n");
      out.write("                    </td>\r\n");
      out.write("                    <td>");
      out.print(doc.get("group_name", ""));
      out.write("</td>\r\n");
      out.write("                    <td>");
      out.print(doc.get("gym_name", ""));
      out.write("</td> \r\n");
      out.write("                    <td>");
      out.print(doc.get("username"));
      out.write("\r\n");
      out.write("                    </td>\r\n");
      out.write("                    <td>");
      out.print(doc.get("order_no", "") );
      out.write("\r\n");
      out.write("                    </td>\r\n");
      out.write("                    <td>\r\n");
      out.write("                    \t");

                    		if(doc.getIn("funds_type")==1){
                    			out.print("充值");
                    		}else if(doc.getIn("funds_type")==2){
                    			out.print("购买商品");
                    		}
                    	
      out.write("\r\n");
      out.write("                    </td>\r\n");
      out.write("                     <td>");
if(doc.getIn("in_or_de")==1){
                    	 out.print("增加");
                     }else if(doc.getIn("in_or_de")==-1){
                    	 out.print("减少");
                     }
      out.write("</td>\r\n");
      out.write("                    <td>");
      out.print(df.format(AjaxXml.getDouble(doc.get("funds_money", "0")) / 100) );
      out.write("元</td>\r\n");
      out.write("                    <td>");
      out.print(doc.getIn("create_time") != 0 ? AjaxXml.timeStamp2Date(doc.getIn("create_time"), "YY04-MM-DD HH:MI:SS") : "");
      out.write("\r\n");
      out.write("                    </td>\r\n");
      out.write("                   ");
      out.write("\r\n");
      out.write("                </tr>\r\n");
      out.write("                ");

                        }
                    }
                
      out.write("\r\n");
      out.write("                <tr>\r\n");
      out.write("                <td colspan=\"7\" style=\"text-align: center;\">\r\n");
      out.write("                \t总增加：&nbsp;<em style=\"color:red;\">");
      out.print(df.format(bd_in.doubleValue()/100) );
      out.write(" 元</em>&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;\r\n");
      out.write("                \t总减少：&nbsp;<em style=\"color:red;\">");
      out.print(df.format(bd_de.doubleValue()/100) );
      out.write(" 元</em>\r\n");
      out.write("                </td>\r\n");
      out.write("                    <td colspan=\"2\" style=\"text-align: right\">\r\n");
      out.write("                        ");

                            out.print(AjaxXml.getPage(pages, 10, pn, counts, "", "", "",
                                    request));
                        
      out.write("\r\n");
      out.write("                    </td>\r\n");
      out.write("                </tr>\r\n");
      out.write("            </table>\r\n");
      out.write("        </form>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<!--r_iframe END-->\r\n");
      out.write("\r\n");
      out.write("<div style=\"display:none\"></div>");
      out.write("<!--End Sidebar-->\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("    $(document).ready(getGyms('select[name=gymGroupId]', '");
      out.print(gymId);
      out.write("'));\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
